// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimPendingUser = `-- name: ClaimPendingUser :one
UPDATE users
SET provider    = $2,
    provider_id = $3,
    name        = $4,
    updated_at  = NOW()
WHERE email = $1
  AND provider = 'pending'
RETURNING id, provider, provider_id, email, name, role, created_at, updated_at, org_id
`

type ClaimPendingUserParams struct {
	Email      string `json:"email"`
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
	Name       string `json:"name"`
}

func (q *Queries) ClaimPendingUser(ctx context.Context, arg ClaimPendingUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, claimPendingUser,
		arg.Email,
		arg.Provider,
		arg.ProviderID,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, provider, provider_id, email, name, role, created_at, updated_at, org_id FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, provider, provider_id, email, name, role, created_at, updated_at, org_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT
    u.id         AS user_id,
    u.name,
    u.email,
    u.role,
    COUNT(s.token)::bigint     AS session_count,
    MAX(s.expiry)::timestamptz AS expires_at
FROM users u
JOIN sessions s ON s.user_id = u.id
WHERE s.expiry > NOW()
GROUP BY u.id, u.name, u.email, u.role
ORDER BY expires_at DESC
`

type ListActiveSessionsByUserRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	Role         string    `json:"role"`
	SessionCount int64     `json:"session_count"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) ListActiveSessionsByUser(ctx context.Context) ([]ListActiveSessionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessionsByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSessionsByUserRow
	for rows.Next() {
		var i ListActiveSessionsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.SessionCount,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevStubUsers = `-- name: ListDevStubUsers :many
SELECT id, provider, provider_id, email, name, role, created_at, updated_at, org_id FROM users
WHERE provider = 'dev_stub'
ORDER BY
    CASE role
        WHEN 'admin' THEN 0
        WHEN 'editor' THEN 1
        WHEN 'contributor' THEN 2
        WHEN 'viewer' THEN 3
        ELSE 4
    END,
    created_at ASC
`

func (q *Queries) ListDevStubUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listDevStubUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, provider, provider_id, email, name, role, created_at, updated_at, org_id FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const preCreateUser = `-- name: PreCreateUser :one
INSERT INTO users (provider, provider_id, email, name, role)
VALUES ('pending', $1, $1, $2, $3)
ON CONFLICT (provider, provider_id) DO UPDATE
    SET role       = EXCLUDED.role,
        name       = EXCLUDED.name,
        updated_at = NOW()
RETURNING id, provider, provider_id, email, name, role, created_at, updated_at, org_id
`

type PreCreateUserParams struct {
	ProviderID string `json:"provider_id"`
	Name       string `json:"name"`
	Role       string `json:"role"`
}

func (q *Queries) PreCreateUser(ctx context.Context, arg PreCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, preCreateUser, arg.ProviderID, arg.Name, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const setUserOrg = `-- name: SetUserOrg :one
UPDATE users SET org_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, provider, provider_id, email, name, role, created_at, updated_at, org_id
`

type SetUserOrgParams struct {
	ID    uuid.UUID     `json:"id"`
	OrgID uuid.NullUUID `json:"org_id"`
}

func (q *Queries) SetUserOrg(ctx context.Context, arg SetUserOrgParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserOrg, arg.ID, arg.OrgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, provider, provider_id, email, name, role, created_at, updated_at, org_id
`

type SetUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const upsertDevStubUser = `-- name: UpsertDevStubUser :one
INSERT INTO users (provider, provider_id, email, name, role)
VALUES ('dev_stub', $1, $2, $3, $4)
ON CONFLICT (provider, provider_id) DO UPDATE
    SET email      = EXCLUDED.email,
        name       = EXCLUDED.name,
        role       = EXCLUDED.role,
        updated_at = NOW()
RETURNING id, provider, provider_id, email, name, role, created_at, updated_at, org_id
`

type UpsertDevStubUserParams struct {
	ProviderID string `json:"provider_id"`
	Email      string `json:"email"`
	Name       string `json:"name"`
	Role       string `json:"role"`
}

func (q *Queries) UpsertDevStubUser(ctx context.Context, arg UpsertDevStubUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertDevStubUser,
		arg.ProviderID,
		arg.Email,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (provider, provider_id, email, name, role)
VALUES ($1, $2, $3, $4,
    CASE WHEN (SELECT COUNT(*) FROM users) = 0 THEN 'admin' ELSE 'viewer' END
)
ON CONFLICT (provider, provider_id) DO UPDATE
    SET email      = EXCLUDED.email,
        name       = EXCLUDED.name,
        updated_at = NOW()
RETURNING id, provider, provider_id, email, name, role, created_at, updated_at, org_id
`

type UpsertUserParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
	Email      string `json:"email"`
	Name       string `json:"name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}
