// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: avvik.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addAvvikAttachment = `-- name: AddAvvikAttachment :one
INSERT INTO avvik_attachments (avvik_id, filename, storage_key, uploaded_by)
VALUES ($1, $2, $3, $4)
RETURNING id, avvik_id, filename, storage_key, uploaded_by, uploaded_at
`

type AddAvvikAttachmentParams struct {
	AvvikID    uuid.UUID     `json:"avvik_id"`
	Filename   string        `json:"filename"`
	StorageKey string        `json:"storage_key"`
	UploadedBy uuid.NullUUID `json:"uploaded_by"`
}

func (q *Queries) AddAvvikAttachment(ctx context.Context, arg AddAvvikAttachmentParams) (AvvikAttachment, error) {
	row := q.db.QueryRowContext(ctx, addAvvikAttachment,
		arg.AvvikID,
		arg.Filename,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i AvvikAttachment
	err := row.Scan(
		&i.ID,
		&i.AvvikID,
		&i.Filename,
		&i.StorageKey,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const addAvvikEvent = `-- name: AddAvvikEvent :one
INSERT INTO avvik_events (avvik_id, actor_id, actor_label, event_type, payload, occurred_at, import_source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, avvik_id, actor_id, actor_label, event_type, payload, occurred_at, import_source
`

type AddAvvikEventParams struct {
	AvvikID      uuid.UUID       `json:"avvik_id"`
	ActorID      uuid.NullUUID   `json:"actor_id"`
	ActorLabel   string          `json:"actor_label"`
	EventType    string          `json:"event_type"`
	Payload      json.RawMessage `json:"payload"`
	OccurredAt   time.Time       `json:"occurred_at"`
	ImportSource sql.NullString  `json:"import_source"`
}

func (q *Queries) AddAvvikEvent(ctx context.Context, arg AddAvvikEventParams) (AvvikEvent, error) {
	row := q.db.QueryRowContext(ctx, addAvvikEvent,
		arg.AvvikID,
		arg.ActorID,
		arg.ActorLabel,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
		arg.ImportSource,
	)
	var i AvvikEvent
	err := row.Scan(
		&i.ID,
		&i.AvvikID,
		&i.ActorID,
		&i.ActorLabel,
		&i.EventType,
		&i.Payload,
		&i.OccurredAt,
		&i.ImportSource,
	)
	return i, err
}

const addAvvikNotification = `-- name: AddAvvikNotification :one
INSERT INTO avvik_notifications (avvik_id, audience, sent_at, sent_by, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, avvik_id, audience, sent_at, sent_by, notes
`

type AddAvvikNotificationParams struct {
	AvvikID  uuid.UUID     `json:"avvik_id"`
	Audience string        `json:"audience"`
	SentAt   time.Time     `json:"sent_at"`
	SentBy   uuid.NullUUID `json:"sent_by"`
	Notes    string        `json:"notes"`
}

func (q *Queries) AddAvvikNotification(ctx context.Context, arg AddAvvikNotificationParams) (AvvikNotification, error) {
	row := q.db.QueryRowContext(ctx, addAvvikNotification,
		arg.AvvikID,
		arg.Audience,
		arg.SentAt,
		arg.SentBy,
		arg.Notes,
	)
	var i AvvikNotification
	err := row.Scan(
		&i.ID,
		&i.AvvikID,
		&i.Audience,
		&i.SentAt,
		&i.SentBy,
		&i.Notes,
	)
	return i, err
}

const createAvvik = `-- name: CreateAvvik :one
INSERT INTO avvik (
    title, description, discovered_at, reported_at, reporter_name, reporter_email,
    assigned_to, org_unit_id, risk_level, status, personal_data, ksi, ksi_information_owner,
    market_sensitive, market_assessment_note, gdpr_deadline_at, realised_risk_id,
    import_source, external_reference, imported_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20
)
RETURNING id, title, description, discovered_at, reported_at, reporter_name, reporter_email, assigned_to, org_unit_id, risk_level, status, personal_data, ksi, ksi_information_owner, market_sensitive, market_assessment_note, gdpr_deadline_at, realised_risk_id, root_cause, lessons_learned, log_qa_done, followups_delegated, reporter_informed, org_informed, mgmt_informed, decisions_anchored, implementation_deadline_set, closure_summary, closed_at, external_reference, import_source, imported_at, created_at, updated_at
`

type CreateAvvikParams struct {
	Title                string         `json:"title"`
	Description          string         `json:"description"`
	DiscoveredAt         time.Time      `json:"discovered_at"`
	ReportedAt           sql.NullTime   `json:"reported_at"`
	ReporterName         string         `json:"reporter_name"`
	ReporterEmail        string         `json:"reporter_email"`
	AssignedTo           uuid.NullUUID  `json:"assigned_to"`
	OrgUnitID            uuid.NullUUID  `json:"org_unit_id"`
	RiskLevel            string         `json:"risk_level"`
	Status               string         `json:"status"`
	PersonalData         bool           `json:"personal_data"`
	Ksi                  bool           `json:"ksi"`
	KsiInformationOwner  string         `json:"ksi_information_owner"`
	MarketSensitive      bool           `json:"market_sensitive"`
	MarketAssessmentNote string         `json:"market_assessment_note"`
	GdprDeadlineAt       sql.NullTime   `json:"gdpr_deadline_at"`
	RealisedRiskID       uuid.NullUUID  `json:"realised_risk_id"`
	ImportSource         sql.NullString `json:"import_source"`
	ExternalReference    string         `json:"external_reference"`
	ImportedAt           sql.NullTime   `json:"imported_at"`
}

func (q *Queries) CreateAvvik(ctx context.Context, arg CreateAvvikParams) (Avvik, error) {
	row := q.db.QueryRowContext(ctx, createAvvik,
		arg.Title,
		arg.Description,
		arg.DiscoveredAt,
		arg.ReportedAt,
		arg.ReporterName,
		arg.ReporterEmail,
		arg.AssignedTo,
		arg.OrgUnitID,
		arg.RiskLevel,
		arg.Status,
		arg.PersonalData,
		arg.Ksi,
		arg.KsiInformationOwner,
		arg.MarketSensitive,
		arg.MarketAssessmentNote,
		arg.GdprDeadlineAt,
		arg.RealisedRiskID,
		arg.ImportSource,
		arg.ExternalReference,
		arg.ImportedAt,
	)
	var i Avvik
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DiscoveredAt,
		&i.ReportedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.AssignedTo,
		&i.OrgUnitID,
		&i.RiskLevel,
		&i.Status,
		&i.PersonalData,
		&i.Ksi,
		&i.KsiInformationOwner,
		&i.MarketSensitive,
		&i.MarketAssessmentNote,
		&i.GdprDeadlineAt,
		&i.RealisedRiskID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.LogQaDone,
		&i.FollowupsDelegated,
		&i.ReporterInformed,
		&i.OrgInformed,
		&i.MgmtInformed,
		&i.DecisionsAnchored,
		&i.ImplementationDeadlineSet,
		&i.ClosureSummary,
		&i.ClosedAt,
		&i.ExternalReference,
		&i.ImportSource,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvvik = `-- name: GetAvvik :one
SELECT id, title, description, discovered_at, reported_at, reporter_name, reporter_email, assigned_to, org_unit_id, risk_level, status, personal_data, ksi, ksi_information_owner, market_sensitive, market_assessment_note, gdpr_deadline_at, realised_risk_id, root_cause, lessons_learned, log_qa_done, followups_delegated, reporter_informed, org_informed, mgmt_informed, decisions_anchored, implementation_deadline_set, closure_summary, closed_at, external_reference, import_source, imported_at, created_at, updated_at FROM avvik WHERE id = $1
`

func (q *Queries) GetAvvik(ctx context.Context, id uuid.UUID) (Avvik, error) {
	row := q.db.QueryRowContext(ctx, getAvvik, id)
	var i Avvik
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DiscoveredAt,
		&i.ReportedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.AssignedTo,
		&i.OrgUnitID,
		&i.RiskLevel,
		&i.Status,
		&i.PersonalData,
		&i.Ksi,
		&i.KsiInformationOwner,
		&i.MarketSensitive,
		&i.MarketAssessmentNote,
		&i.GdprDeadlineAt,
		&i.RealisedRiskID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.LogQaDone,
		&i.FollowupsDelegated,
		&i.ReporterInformed,
		&i.OrgInformed,
		&i.MgmtInformed,
		&i.DecisionsAnchored,
		&i.ImplementationDeadlineSet,
		&i.ClosureSummary,
		&i.ClosedAt,
		&i.ExternalReference,
		&i.ImportSource,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkAvvikActivity = `-- name: LinkAvvikActivity :exec
INSERT INTO avvik_activities (avvik_id, activity_id)
VALUES ($1, $2)
ON CONFLICT (avvik_id, activity_id) DO NOTHING
`

type LinkAvvikActivityParams struct {
	AvvikID    uuid.UUID `json:"avvik_id"`
	ActivityID uuid.UUID `json:"activity_id"`
}

func (q *Queries) LinkAvvikActivity(ctx context.Context, arg LinkAvvikActivityParams) error {
	_, err := q.db.ExecContext(ctx, linkAvvikActivity, arg.AvvikID, arg.ActivityID)
	return err
}

const linkAvvikMeasure = `-- name: LinkAvvikMeasure :exec
INSERT INTO avvik_measures (avvik_id, measure_id, relationship)
VALUES ($1, $2, $3)
ON CONFLICT (avvik_id, measure_id) DO UPDATE SET relationship = EXCLUDED.relationship
`

type LinkAvvikMeasureParams struct {
	AvvikID      uuid.UUID `json:"avvik_id"`
	MeasureID    uuid.UUID `json:"measure_id"`
	Relationship string    `json:"relationship"`
}

func (q *Queries) LinkAvvikMeasure(ctx context.Context, arg LinkAvvikMeasureParams) error {
	_, err := q.db.ExecContext(ctx, linkAvvikMeasure, arg.AvvikID, arg.MeasureID, arg.Relationship)
	return err
}

const listAvvik = `-- name: ListAvvik :many
SELECT id, title, description, discovered_at, reported_at, reporter_name, reporter_email, assigned_to, org_unit_id, risk_level, status, personal_data, ksi, ksi_information_owner, market_sensitive, market_assessment_note, gdpr_deadline_at, realised_risk_id, root_cause, lessons_learned, log_qa_done, followups_delegated, reporter_informed, org_informed, mgmt_informed, decisions_anchored, implementation_deadline_set, closure_summary, closed_at, external_reference, import_source, imported_at, created_at, updated_at
FROM avvik
WHERE
    ($1::text IS NULL OR status = $1::text) AND
    ($2::text IS NULL OR risk_level = $2::text) AND
    ($3::bool IS NULL OR personal_data = $3::bool) AND
    ($4::bool IS NULL OR ksi = $4::bool) AND
    ($5::bool IS NULL OR market_sensitive = $5::bool) AND
    ($6::uuid IS NULL OR org_unit_id = $6::uuid) AND
    (NOT $7::bool OR assigned_to = $8::uuid) AND
    ($9 = '' OR title ILIKE '%' || $9 || '%' OR description ILIKE '%' || $9 || '%')
ORDER BY updated_at DESC
LIMIT $11
OFFSET $10
`

type ListAvvikParams struct {
	Status          sql.NullString `json:"status"`
	RiskLevel       sql.NullString `json:"risk_level"`
	PersonalData    sql.NullBool   `json:"personal_data"`
	Ksi             sql.NullBool   `json:"ksi"`
	MarketSensitive sql.NullBool   `json:"market_sensitive"`
	OrgUnitID       uuid.NullUUID  `json:"org_unit_id"`
	Mine            bool           `json:"mine"`
	AssigneeID      uuid.UUID      `json:"assignee_id"`
	Q               interface{}    `json:"q"`
	PageOffset      int32          `json:"page_offset"`
	PageSize        int32          `json:"page_size"`
}

func (q *Queries) ListAvvik(ctx context.Context, arg ListAvvikParams) ([]Avvik, error) {
	rows, err := q.db.QueryContext(ctx, listAvvik,
		arg.Status,
		arg.RiskLevel,
		arg.PersonalData,
		arg.Ksi,
		arg.MarketSensitive,
		arg.OrgUnitID,
		arg.Mine,
		arg.AssigneeID,
		arg.Q,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Avvik
	for rows.Next() {
		var i Avvik
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DiscoveredAt,
			&i.ReportedAt,
			&i.ReporterName,
			&i.ReporterEmail,
			&i.AssignedTo,
			&i.OrgUnitID,
			&i.RiskLevel,
			&i.Status,
			&i.PersonalData,
			&i.Ksi,
			&i.KsiInformationOwner,
			&i.MarketSensitive,
			&i.MarketAssessmentNote,
			&i.GdprDeadlineAt,
			&i.RealisedRiskID,
			&i.RootCause,
			&i.LessonsLearned,
			&i.LogQaDone,
			&i.FollowupsDelegated,
			&i.ReporterInformed,
			&i.OrgInformed,
			&i.MgmtInformed,
			&i.DecisionsAnchored,
			&i.ImplementationDeadlineSet,
			&i.ClosureSummary,
			&i.ClosedAt,
			&i.ExternalReference,
			&i.ImportSource,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvvikActivities = `-- name: ListAvvikActivities :many
SELECT a.id, a.measure_id, a.title, a.description, a.activity_type, a.recurrence, a.status, a.owner, a.due_date, a.completed_at, a.completed_by, a.notes, a.evidence_url, a.parent_activity_id, a.created_at, a.updated_at, a.assignee_id, a.priority, a.kind, a.ref_num
FROM avvik_activities aa
JOIN activities a ON a.id = aa.activity_id
WHERE aa.avvik_id = $1
ORDER BY a.updated_at DESC
`

func (q *Queries) ListAvvikActivities(ctx context.Context, avvikID uuid.UUID) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listAvvikActivities, avvikID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.MeasureID,
			&i.Title,
			&i.Description,
			&i.ActivityType,
			&i.Recurrence,
			&i.Status,
			&i.Owner,
			&i.DueDate,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.Notes,
			&i.EvidenceUrl,
			&i.ParentActivityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneeID,
			&i.Priority,
			&i.Kind,
			&i.RefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvvikAttachments = `-- name: ListAvvikAttachments :many
SELECT id, avvik_id, filename, storage_key, uploaded_by, uploaded_at FROM avvik_attachments WHERE avvik_id = $1 ORDER BY uploaded_at DESC
`

func (q *Queries) ListAvvikAttachments(ctx context.Context, avvikID uuid.UUID) ([]AvvikAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listAvvikAttachments, avvikID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvvikAttachment
	for rows.Next() {
		var i AvvikAttachment
		if err := rows.Scan(
			&i.ID,
			&i.AvvikID,
			&i.Filename,
			&i.StorageKey,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvvikEvents = `-- name: ListAvvikEvents :many
SELECT id, avvik_id, actor_id, actor_label, event_type, payload, occurred_at, import_source FROM avvik_events WHERE avvik_id = $1 ORDER BY occurred_at DESC
`

func (q *Queries) ListAvvikEvents(ctx context.Context, avvikID uuid.UUID) ([]AvvikEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAvvikEvents, avvikID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvvikEvent
	for rows.Next() {
		var i AvvikEvent
		if err := rows.Scan(
			&i.ID,
			&i.AvvikID,
			&i.ActorID,
			&i.ActorLabel,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
			&i.ImportSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvvikMeasures = `-- name: ListAvvikMeasures :many
SELECT m.id, m.name, m.description, m.category, m.owner, m.status, m.created_at, m.updated_at, m.last_verified_at, m.assignee_id, m.ref_num
FROM avvik_measures am
JOIN measures m ON m.id = am.measure_id
WHERE am.avvik_id = $1
ORDER BY m.updated_at DESC
`

func (q *Queries) ListAvvikMeasures(ctx context.Context, avvikID uuid.UUID) ([]Measure, error) {
	rows, err := q.db.QueryContext(ctx, listAvvikMeasures, avvikID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measure
	for rows.Next() {
		var i Measure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Owner,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastVerifiedAt,
			&i.AssigneeID,
			&i.RefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvvikNotifications = `-- name: ListAvvikNotifications :many
SELECT id, avvik_id, audience, sent_at, sent_by, notes FROM avvik_notifications WHERE avvik_id = $1 ORDER BY sent_at DESC
`

func (q *Queries) ListAvvikNotifications(ctx context.Context, avvikID uuid.UUID) ([]AvvikNotification, error) {
	rows, err := q.db.QueryContext(ctx, listAvvikNotifications, avvikID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvvikNotification
	for rows.Next() {
		var i AvvikNotification
		if err := rows.Scan(
			&i.ID,
			&i.AvvikID,
			&i.Audience,
			&i.SentAt,
			&i.SentBy,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkAvvikActivity = `-- name: UnlinkAvvikActivity :exec
DELETE FROM avvik_activities WHERE avvik_id = $1 AND activity_id = $2
`

type UnlinkAvvikActivityParams struct {
	AvvikID    uuid.UUID `json:"avvik_id"`
	ActivityID uuid.UUID `json:"activity_id"`
}

func (q *Queries) UnlinkAvvikActivity(ctx context.Context, arg UnlinkAvvikActivityParams) error {
	_, err := q.db.ExecContext(ctx, unlinkAvvikActivity, arg.AvvikID, arg.ActivityID)
	return err
}

const unlinkAvvikMeasure = `-- name: UnlinkAvvikMeasure :exec
DELETE FROM avvik_measures WHERE avvik_id = $1 AND measure_id = $2
`

type UnlinkAvvikMeasureParams struct {
	AvvikID   uuid.UUID `json:"avvik_id"`
	MeasureID uuid.UUID `json:"measure_id"`
}

func (q *Queries) UnlinkAvvikMeasure(ctx context.Context, arg UnlinkAvvikMeasureParams) error {
	_, err := q.db.ExecContext(ctx, unlinkAvvikMeasure, arg.AvvikID, arg.MeasureID)
	return err
}

const updateAvvikClosureFlags = `-- name: UpdateAvvikClosureFlags :one
UPDATE avvik
SET log_qa_done = $2,
    followups_delegated = $3,
    reporter_informed = $4,
    org_informed = $5,
    mgmt_informed = $6,
    decisions_anchored = $7,
    implementation_deadline_set = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, discovered_at, reported_at, reporter_name, reporter_email, assigned_to, org_unit_id, risk_level, status, personal_data, ksi, ksi_information_owner, market_sensitive, market_assessment_note, gdpr_deadline_at, realised_risk_id, root_cause, lessons_learned, log_qa_done, followups_delegated, reporter_informed, org_informed, mgmt_informed, decisions_anchored, implementation_deadline_set, closure_summary, closed_at, external_reference, import_source, imported_at, created_at, updated_at
`

type UpdateAvvikClosureFlagsParams struct {
	ID                        uuid.UUID `json:"id"`
	LogQaDone                 bool      `json:"log_qa_done"`
	FollowupsDelegated        bool      `json:"followups_delegated"`
	ReporterInformed          bool      `json:"reporter_informed"`
	OrgInformed               bool      `json:"org_informed"`
	MgmtInformed              bool      `json:"mgmt_informed"`
	DecisionsAnchored         bool      `json:"decisions_anchored"`
	ImplementationDeadlineSet bool      `json:"implementation_deadline_set"`
}

func (q *Queries) UpdateAvvikClosureFlags(ctx context.Context, arg UpdateAvvikClosureFlagsParams) (Avvik, error) {
	row := q.db.QueryRowContext(ctx, updateAvvikClosureFlags,
		arg.ID,
		arg.LogQaDone,
		arg.FollowupsDelegated,
		arg.ReporterInformed,
		arg.OrgInformed,
		arg.MgmtInformed,
		arg.DecisionsAnchored,
		arg.ImplementationDeadlineSet,
	)
	var i Avvik
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DiscoveredAt,
		&i.ReportedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.AssignedTo,
		&i.OrgUnitID,
		&i.RiskLevel,
		&i.Status,
		&i.PersonalData,
		&i.Ksi,
		&i.KsiInformationOwner,
		&i.MarketSensitive,
		&i.MarketAssessmentNote,
		&i.GdprDeadlineAt,
		&i.RealisedRiskID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.LogQaDone,
		&i.FollowupsDelegated,
		&i.ReporterInformed,
		&i.OrgInformed,
		&i.MgmtInformed,
		&i.DecisionsAnchored,
		&i.ImplementationDeadlineSet,
		&i.ClosureSummary,
		&i.ClosedAt,
		&i.ExternalReference,
		&i.ImportSource,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAvvikStatus = `-- name: UpdateAvvikStatus :one
UPDATE avvik
SET status = $2,
    closed_at = $3,
    closure_summary = $4,
    root_cause = $5,
    lessons_learned = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, discovered_at, reported_at, reporter_name, reporter_email, assigned_to, org_unit_id, risk_level, status, personal_data, ksi, ksi_information_owner, market_sensitive, market_assessment_note, gdpr_deadline_at, realised_risk_id, root_cause, lessons_learned, log_qa_done, followups_delegated, reporter_informed, org_informed, mgmt_informed, decisions_anchored, implementation_deadline_set, closure_summary, closed_at, external_reference, import_source, imported_at, created_at, updated_at
`

type UpdateAvvikStatusParams struct {
	ID             uuid.UUID    `json:"id"`
	Status         string       `json:"status"`
	ClosedAt       sql.NullTime `json:"closed_at"`
	ClosureSummary string       `json:"closure_summary"`
	RootCause      string       `json:"root_cause"`
	LessonsLearned string       `json:"lessons_learned"`
}

func (q *Queries) UpdateAvvikStatus(ctx context.Context, arg UpdateAvvikStatusParams) (Avvik, error) {
	row := q.db.QueryRowContext(ctx, updateAvvikStatus,
		arg.ID,
		arg.Status,
		arg.ClosedAt,
		arg.ClosureSummary,
		arg.RootCause,
		arg.LessonsLearned,
	)
	var i Avvik
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DiscoveredAt,
		&i.ReportedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.AssignedTo,
		&i.OrgUnitID,
		&i.RiskLevel,
		&i.Status,
		&i.PersonalData,
		&i.Ksi,
		&i.KsiInformationOwner,
		&i.MarketSensitive,
		&i.MarketAssessmentNote,
		&i.GdprDeadlineAt,
		&i.RealisedRiskID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.LogQaDone,
		&i.FollowupsDelegated,
		&i.ReporterInformed,
		&i.OrgInformed,
		&i.MgmtInformed,
		&i.DecisionsAnchored,
		&i.ImplementationDeadlineSet,
		&i.ClosureSummary,
		&i.ClosedAt,
		&i.ExternalReference,
		&i.ImportSource,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAvvikTriage = `-- name: UpdateAvvikTriage :one
UPDATE avvik
SET risk_level = $2,
    personal_data = $3,
    ksi = $4,
    ksi_information_owner = $5,
    market_sensitive = $6,
    market_assessment_note = $7,
    gdpr_deadline_at = $8,
    org_unit_id = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, discovered_at, reported_at, reporter_name, reporter_email, assigned_to, org_unit_id, risk_level, status, personal_data, ksi, ksi_information_owner, market_sensitive, market_assessment_note, gdpr_deadline_at, realised_risk_id, root_cause, lessons_learned, log_qa_done, followups_delegated, reporter_informed, org_informed, mgmt_informed, decisions_anchored, implementation_deadline_set, closure_summary, closed_at, external_reference, import_source, imported_at, created_at, updated_at
`

type UpdateAvvikTriageParams struct {
	ID                   uuid.UUID     `json:"id"`
	RiskLevel            string        `json:"risk_level"`
	PersonalData         bool          `json:"personal_data"`
	Ksi                  bool          `json:"ksi"`
	KsiInformationOwner  string        `json:"ksi_information_owner"`
	MarketSensitive      bool          `json:"market_sensitive"`
	MarketAssessmentNote string        `json:"market_assessment_note"`
	GdprDeadlineAt       sql.NullTime  `json:"gdpr_deadline_at"`
	OrgUnitID            uuid.NullUUID `json:"org_unit_id"`
}

func (q *Queries) UpdateAvvikTriage(ctx context.Context, arg UpdateAvvikTriageParams) (Avvik, error) {
	row := q.db.QueryRowContext(ctx, updateAvvikTriage,
		arg.ID,
		arg.RiskLevel,
		arg.PersonalData,
		arg.Ksi,
		arg.KsiInformationOwner,
		arg.MarketSensitive,
		arg.MarketAssessmentNote,
		arg.GdprDeadlineAt,
		arg.OrgUnitID,
	)
	var i Avvik
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DiscoveredAt,
		&i.ReportedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.AssignedTo,
		&i.OrgUnitID,
		&i.RiskLevel,
		&i.Status,
		&i.PersonalData,
		&i.Ksi,
		&i.KsiInformationOwner,
		&i.MarketSensitive,
		&i.MarketAssessmentNote,
		&i.GdprDeadlineAt,
		&i.RealisedRiskID,
		&i.RootCause,
		&i.LessonsLearned,
		&i.LogQaDone,
		&i.FollowupsDelegated,
		&i.ReporterInformed,
		&i.OrgInformed,
		&i.MgmtInformed,
		&i.DecisionsAnchored,
		&i.ImplementationDeadlineSet,
		&i.ClosureSummary,
		&i.ClosedAt,
		&i.ExternalReference,
		&i.ImportSource,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
