// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countCoveredRequirementsByFramework = `-- name: CountCoveredRequirementsByFramework :one
SELECT COUNT(DISTINCT r.id)::bigint
FROM requirements r
INNER JOIN measure_requirements mr ON r.id = mr.requirement_id
INNER JOIN measures m ON mr.measure_id = m.id
WHERE r.framework_id = $1
  AND m.status = 'implemented'
  AND NOT r.not_relevant
`

func (q *Queries) CountCoveredRequirementsByFramework(ctx context.Context, frameworkID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCoveredRequirementsByFramework, frameworkID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRequirementsByFramework = `-- name: CountRequirementsByFramework :one
SELECT COUNT(*)::bigint FROM requirements WHERE framework_id = $1 AND NOT not_relevant
`

func (q *Queries) CountRequirementsByFramework(ctx context.Context, frameworkID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequirementsByFramework, frameworkID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createFramework = `-- name: CreateFramework :one
INSERT INTO frameworks (name, short_name, version, description, framework_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, short_name, version, description, created_at, updated_at, framework_type, not_relevant, not_relevant_reason
`

type CreateFrameworkParams struct {
	Name          string `json:"name"`
	ShortName     string `json:"short_name"`
	Version       string `json:"version"`
	Description   string `json:"description"`
	FrameworkType string `json:"framework_type"`
}

func (q *Queries) CreateFramework(ctx context.Context, arg CreateFrameworkParams) (Framework, error) {
	row := q.db.QueryRowContext(ctx, createFramework,
		arg.Name,
		arg.ShortName,
		arg.Version,
		arg.Description,
		arg.FrameworkType,
	)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FrameworkType,
		&i.NotRelevant,
		&i.NotRelevantReason,
	)
	return i, err
}

const createRequirement = `-- name: CreateRequirement :one
INSERT INTO requirements (framework_id, ref, title, description, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, framework_id, ref, title, description, sort_order, created_at, updated_at, not_relevant, not_relevant_reason
`

type CreateRequirementParams struct {
	FrameworkID uuid.UUID `json:"framework_id"`
	Ref         string    `json:"ref"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) CreateRequirement(ctx context.Context, arg CreateRequirementParams) (Requirement, error) {
	row := q.db.QueryRowContext(ctx, createRequirement,
		arg.FrameworkID,
		arg.Ref,
		arg.Title,
		arg.Description,
		arg.SortOrder,
	)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.Ref,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NotRelevant,
		&i.NotRelevantReason,
	)
	return i, err
}

const deleteFramework = `-- name: DeleteFramework :exec
DELETE FROM frameworks WHERE id = $1
`

func (q *Queries) DeleteFramework(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFramework, id)
	return err
}

const deleteRequirement = `-- name: DeleteRequirement :exec
DELETE FROM requirements WHERE id = $1
`

func (q *Queries) DeleteRequirement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRequirement, id)
	return err
}

const getFramework = `-- name: GetFramework :one
SELECT id, name, short_name, version, description, created_at, updated_at, framework_type, not_relevant, not_relevant_reason FROM frameworks WHERE id = $1
`

func (q *Queries) GetFramework(ctx context.Context, id uuid.UUID) (Framework, error) {
	row := q.db.QueryRowContext(ctx, getFramework, id)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FrameworkType,
		&i.NotRelevant,
		&i.NotRelevantReason,
	)
	return i, err
}

const getRequirement = `-- name: GetRequirement :one
SELECT id, framework_id, ref, title, description, sort_order, created_at, updated_at, not_relevant, not_relevant_reason
FROM requirements
WHERE id = $1
`

func (q *Queries) GetRequirement(ctx context.Context, id uuid.UUID) (Requirement, error) {
	row := q.db.QueryRowContext(ctx, getRequirement, id)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.Ref,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NotRelevant,
		&i.NotRelevantReason,
	)
	return i, err
}

const listFrameworks = `-- name: ListFrameworks :many
SELECT id, name, short_name, version, description, created_at, updated_at, framework_type, not_relevant, not_relevant_reason FROM frameworks ORDER BY name
`

func (q *Queries) ListFrameworks(ctx context.Context) ([]Framework, error) {
	rows, err := q.db.QueryContext(ctx, listFrameworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Framework
	for rows.Next() {
		var i Framework
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Version,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FrameworkType,
			&i.NotRelevant,
			&i.NotRelevantReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasuresForRequirement = `-- name: ListMeasuresForRequirement :many
SELECT m.id, m.name, m.category, m.status, m.owner
FROM measures m
INNER JOIN measure_requirements mr ON m.id = mr.measure_id
WHERE mr.requirement_id = $1
ORDER BY m.name
`

type ListMeasuresForRequirementRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Category string    `json:"category"`
	Status   string    `json:"status"`
	Owner    string    `json:"owner"`
}

func (q *Queries) ListMeasuresForRequirement(ctx context.Context, requirementID uuid.UUID) ([]ListMeasuresForRequirementRow, error) {
	rows, err := q.db.QueryContext(ctx, listMeasuresForRequirement, requirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeasuresForRequirementRow
	for rows.Next() {
		var i ListMeasuresForRequirementRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementsByFramework = `-- name: ListRequirementsByFramework :many
SELECT id, framework_id, ref, title, description, sort_order, created_at, updated_at, not_relevant, not_relevant_reason
FROM requirements
WHERE framework_id = $1
ORDER BY sort_order, ref
`

func (q *Queries) ListRequirementsByFramework(ctx context.Context, frameworkID uuid.UUID) ([]Requirement, error) {
	rows, err := q.db.QueryContext(ctx, listRequirementsByFramework, frameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Requirement
	for rows.Next() {
		var i Requirement
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkID,
			&i.Ref,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NotRelevant,
			&i.NotRelevantReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFramework = `-- name: UpdateFramework :one
UPDATE frameworks
SET name = $2, short_name = $3, version = $4, description = $5, framework_type = $6,
    not_relevant = $7, not_relevant_reason = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, name, short_name, version, description, created_at, updated_at, framework_type, not_relevant, not_relevant_reason
`

type UpdateFrameworkParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	ShortName         string    `json:"short_name"`
	Version           string    `json:"version"`
	Description       string    `json:"description"`
	FrameworkType     string    `json:"framework_type"`
	NotRelevant       bool      `json:"not_relevant"`
	NotRelevantReason string    `json:"not_relevant_reason"`
}

func (q *Queries) UpdateFramework(ctx context.Context, arg UpdateFrameworkParams) (Framework, error) {
	row := q.db.QueryRowContext(ctx, updateFramework,
		arg.ID,
		arg.Name,
		arg.ShortName,
		arg.Version,
		arg.Description,
		arg.FrameworkType,
		arg.NotRelevant,
		arg.NotRelevantReason,
	)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FrameworkType,
		&i.NotRelevant,
		&i.NotRelevantReason,
	)
	return i, err
}

const updateRequirement = `-- name: UpdateRequirement :one
UPDATE requirements
SET ref = $2, title = $3, description = $4, sort_order = $5,
    not_relevant = $6, not_relevant_reason = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, framework_id, ref, title, description, sort_order, created_at, updated_at, not_relevant, not_relevant_reason
`

type UpdateRequirementParams struct {
	ID                uuid.UUID `json:"id"`
	Ref               string    `json:"ref"`
	Title             string    `json:"title"`
	Description       string    `json:"description"`
	SortOrder         int32     `json:"sort_order"`
	NotRelevant       bool      `json:"not_relevant"`
	NotRelevantReason string    `json:"not_relevant_reason"`
}

func (q *Queries) UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (Requirement, error) {
	row := q.db.QueryRowContext(ctx, updateRequirement,
		arg.ID,
		arg.Ref,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.NotRelevant,
		arg.NotRelevantReason,
	)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.Ref,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NotRelevant,
		&i.NotRelevantReason,
	)
	return i, err
}
