// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*)::bigint FROM frameworks WHERE NOT not_relevant) AS frameworks_count,
    (SELECT COUNT(*)::bigint FROM requirements r
     INNER JOIN frameworks f ON r.framework_id = f.id
     WHERE NOT r.not_relevant AND NOT f.not_relevant) AS requirements_count,
    (SELECT COUNT(*)::bigint FROM measures)       AS measures_count,
    (SELECT COUNT(*)::bigint FROM measures WHERE status = 'implemented') AS implemented_count,
    (SELECT COUNT(DISTINCT r.id)::bigint
     FROM requirements r
     INNER JOIN frameworks f ON r.framework_id = f.id
     INNER JOIN measure_requirements mr ON r.id = mr.requirement_id
     INNER JOIN measures m ON mr.measure_id = m.id
     WHERE NOT r.not_relevant
       AND NOT f.not_relevant
       AND m.status = 'implemented') AS covered_requirements_count,
    (SELECT COUNT(*)::bigint FROM activities
     WHERE status = 'overdue'
        OR (due_date < CURRENT_DATE AND status NOT IN ('completed', 'overdue'))) AS overdue_activities_count,
    (SELECT COUNT(*)::bigint FROM activities
     WHERE due_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '7 days'
       AND status NOT IN ('completed', 'overdue')) AS activities_due_this_week_count
`

type GetDashboardStatsRow struct {
	FrameworksCount            int64 `json:"frameworks_count"`
	RequirementsCount          int64 `json:"requirements_count"`
	MeasuresCount              int64 `json:"measures_count"`
	ImplementedCount           int64 `json:"implemented_count"`
	CoveredRequirementsCount   int64 `json:"covered_requirements_count"`
	OverdueActivitiesCount     int64 `json:"overdue_activities_count"`
	ActivitiesDueThisWeekCount int64 `json:"activities_due_this_week_count"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.FrameworksCount,
		&i.RequirementsCount,
		&i.MeasuresCount,
		&i.ImplementedCount,
		&i.CoveredRequirementsCount,
		&i.OverdueActivitiesCount,
		&i.ActivitiesDueThisWeekCount,
	)
	return i, err
}
