// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID               uuid.UUID     `json:"id"`
	MeasureID        uuid.NullUUID `json:"measure_id"`
	Title            string        `json:"title"`
	Description      string        `json:"description"`
	ActivityType     string        `json:"activity_type"`
	Recurrence       string        `json:"recurrence"`
	Status           string        `json:"status"`
	Owner            string        `json:"owner"`
	DueDate          sql.NullTime  `json:"due_date"`
	CompletedAt      sql.NullTime  `json:"completed_at"`
	CompletedBy      string        `json:"completed_by"`
	Notes            string        `json:"notes"`
	EvidenceUrl      string        `json:"evidence_url"`
	ParentActivityID uuid.NullUUID `json:"parent_activity_id"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	AssigneeID       uuid.NullUUID `json:"assignee_id"`
	Priority         string        `json:"priority"`
	Kind             string        `json:"kind"`
	RefNum           sql.NullInt32 `json:"ref_num"`
}

type AppSetting struct {
	ID                int32 `json:"id"`
	ComplianceEnabled bool  `json:"compliance_enabled"`
	RiskEnabled       bool  `json:"risk_enabled"`
	ActivitiesEnabled bool  `json:"activities_enabled"`
	AssetsEnabled     bool  `json:"assets_enabled"`
	PlaygroundEnabled bool  `json:"playground_enabled"`
	AvvikEnabled      bool  `json:"avvik_enabled"`
}

type Asset struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	AssetType   string    `json:"asset_type"`
	Owner       string    `json:"owner"`
	Status      string    `json:"status"`
	Criticality string    `json:"criticality"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type AuditLog struct {
	ID        uuid.UUID       `json:"id"`
	EventTime time.Time       `json:"event_time"`
	Event     string          `json:"event"`
	UserID    uuid.NullUUID   `json:"user_id"`
	SourceIp  string          `json:"source_ip"`
	UserAgent string          `json:"user_agent"`
	RequestID string          `json:"request_id"`
	TraceID   string          `json:"trace_id"`
	Attrs     json.RawMessage `json:"attrs"`
}

type Avvik struct {
	ID                        uuid.UUID      `json:"id"`
	Title                     string         `json:"title"`
	Description               string         `json:"description"`
	DiscoveredAt              time.Time      `json:"discovered_at"`
	ReportedAt                sql.NullTime   `json:"reported_at"`
	ReporterName              string         `json:"reporter_name"`
	ReporterEmail             string         `json:"reporter_email"`
	AssignedTo                uuid.NullUUID  `json:"assigned_to"`
	OrgUnitID                 uuid.NullUUID  `json:"org_unit_id"`
	RiskLevel                 string         `json:"risk_level"`
	Status                    string         `json:"status"`
	PersonalData              bool           `json:"personal_data"`
	Ksi                       bool           `json:"ksi"`
	KsiInformationOwner       string         `json:"ksi_information_owner"`
	MarketSensitive           bool           `json:"market_sensitive"`
	MarketAssessmentNote      string         `json:"market_assessment_note"`
	GdprDeadlineAt            sql.NullTime   `json:"gdpr_deadline_at"`
	RealisedRiskID            uuid.NullUUID  `json:"realised_risk_id"`
	RootCause                 string         `json:"root_cause"`
	LessonsLearned            string         `json:"lessons_learned"`
	LogQaDone                 bool           `json:"log_qa_done"`
	FollowupsDelegated        bool           `json:"followups_delegated"`
	ReporterInformed          bool           `json:"reporter_informed"`
	OrgInformed               bool           `json:"org_informed"`
	MgmtInformed              bool           `json:"mgmt_informed"`
	DecisionsAnchored         bool           `json:"decisions_anchored"`
	ImplementationDeadlineSet bool           `json:"implementation_deadline_set"`
	ClosureSummary            string         `json:"closure_summary"`
	ClosedAt                  sql.NullTime   `json:"closed_at"`
	ExternalReference         string         `json:"external_reference"`
	ImportSource              sql.NullString `json:"import_source"`
	ImportedAt                sql.NullTime   `json:"imported_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	UpdatedAt                 time.Time      `json:"updated_at"`
}

type AvvikActivity struct {
	AvvikID    uuid.UUID `json:"avvik_id"`
	ActivityID uuid.UUID `json:"activity_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type AvvikAttachment struct {
	ID         uuid.UUID     `json:"id"`
	AvvikID    uuid.UUID     `json:"avvik_id"`
	Filename   string        `json:"filename"`
	StorageKey string        `json:"storage_key"`
	UploadedBy uuid.NullUUID `json:"uploaded_by"`
	UploadedAt time.Time     `json:"uploaded_at"`
}

type AvvikEvent struct {
	ID           uuid.UUID       `json:"id"`
	AvvikID      uuid.UUID       `json:"avvik_id"`
	ActorID      uuid.NullUUID   `json:"actor_id"`
	ActorLabel   string          `json:"actor_label"`
	EventType    string          `json:"event_type"`
	Payload      json.RawMessage `json:"payload"`
	OccurredAt   time.Time       `json:"occurred_at"`
	ImportSource sql.NullString  `json:"import_source"`
}

type AvvikMeasure struct {
	AvvikID      uuid.UUID `json:"avvik_id"`
	MeasureID    uuid.UUID `json:"measure_id"`
	Relationship string    `json:"relationship"`
	CreatedAt    time.Time `json:"created_at"`
}

type AvvikNotification struct {
	ID       uuid.UUID     `json:"id"`
	AvvikID  uuid.UUID     `json:"avvik_id"`
	Audience string        `json:"audience"`
	SentAt   time.Time     `json:"sent_at"`
	SentBy   uuid.NullUUID `json:"sent_by"`
	Notes    string        `json:"notes"`
}

type Framework struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	ShortName         string    `json:"short_name"`
	Version           string    `json:"version"`
	Description       string    `json:"description"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	FrameworkType     string    `json:"framework_type"`
	NotRelevant       bool      `json:"not_relevant"`
	NotRelevantReason string    `json:"not_relevant_reason"`
}

type Measure struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	Description    string        `json:"description"`
	Category       string        `json:"category"`
	Owner          string        `json:"owner"`
	Status         string        `json:"status"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	LastVerifiedAt sql.NullTime  `json:"last_verified_at"`
	AssigneeID     uuid.NullUUID `json:"assignee_id"`
	RefNum         sql.NullInt32 `json:"ref_num"`
}

type MeasureLink struct {
	ID        uuid.UUID `json:"id"`
	MeasureID uuid.UUID `json:"measure_id"`
	Url       string    `json:"url"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type MeasureRequirement struct {
	MeasureID     uuid.UUID `json:"measure_id"`
	RequirementID uuid.UUID `json:"requirement_id"`
	Note          string    `json:"note"`
	CreatedAt     time.Time `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Key       sql.NullString `json:"key"`
}

type Requirement struct {
	ID                uuid.UUID `json:"id"`
	FrameworkID       uuid.UUID `json:"framework_id"`
	Ref               string    `json:"ref"`
	Title             string    `json:"title"`
	Description       string    `json:"description"`
	SortOrder         int32     `json:"sort_order"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	NotRelevant       bool      `json:"not_relevant"`
	NotRelevantReason string    `json:"not_relevant_reason"`
}

type ResourceParticipant struct {
	ID           uuid.UUID `json:"id"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	UserID       uuid.UUID `json:"user_id"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

type Risk struct {
	ID                   uuid.UUID     `json:"id"`
	AssessmentID         uuid.UUID     `json:"assessment_id"`
	Name                 string        `json:"name"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodTarget     sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget    sql.NullInt32 `json:"consequence_target"`
	RiskDecision         string        `json:"risk_decision"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	Description          string        `json:"description"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
	OwnerID              uuid.NullUUID `json:"owner_id"`
	DecisionNotes        string        `json:"decision_notes"`
	RefNum               sql.NullInt32 `json:"ref_num"`
	ReviewNeeded         bool          `json:"review_needed"`
	ReviewDue            sql.NullTime  `json:"review_due"`
	AssessedAt           sql.NullTime  `json:"assessed_at"`
	AssessedBy           uuid.NullUUID `json:"assessed_by"`
	AssessmentRationale  string        `json:"assessment_rationale"`
}

type RiskActivityLink struct {
	RiskID     uuid.UUID `json:"risk_id"`
	ActivityID uuid.UUID `json:"activity_id"`
	Note       string    `json:"note"`
}

type RiskAssessment struct {
	ID                      uuid.UUID     `json:"id"`
	Name                    string        `json:"name"`
	Scope                   string        `json:"scope"`
	AnalysisObject          string        `json:"analysis_object"`
	SecurityObjectives      string        `json:"security_objectives"`
	BusinessObjectives      string        `json:"business_objectives"`
	Type                    string        `json:"type"`
	Status                  string        `json:"status"`
	CurrentStep             int32         `json:"current_step"`
	LastReviewedAt          sql.NullTime  `json:"last_reviewed_at"`
	CreatedBy               uuid.NullUUID `json:"created_by"`
	CreatedAt               time.Time     `json:"created_at"`
	UpdatedAt               time.Time     `json:"updated_at"`
	RiskOwnerID             uuid.NullUUID `json:"risk_owner_id"`
	OrgID                   uuid.NullUUID `json:"org_id"`
	RefNum                  sql.NullInt32 `json:"ref_num"`
	AcceptanceNote          string        `json:"acceptance_note"`
	IsPublic                bool          `json:"is_public"`
	ThreatAssessmentEnabled bool          `json:"threat_assessment_enabled"`
	ThreatAppDescription    string        `json:"threat_app_description"`
	ThreatInformationFlow   string        `json:"threat_information_flow"`
}

type RiskAssessmentAsset struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	AssetID      uuid.UUID `json:"asset_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type RiskAssessmentParticipant struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	UserID       uuid.UUID `json:"user_id"`
}

type RiskAssetLink struct {
	RiskID    uuid.UUID `json:"risk_id"`
	AssetID   uuid.UUID `json:"asset_id"`
	CreatedAt time.Time `json:"created_at"`
}

type RiskGlobalSetting struct {
	ID                 int32  `json:"id"`
	AcceptanceCriteria string `json:"acceptance_criteria"`
	LowMax             int32  `json:"low_max"`
	HighMin            int32  `json:"high_min"`
}

type RiskMeasureLink struct {
	RiskID    uuid.UUID `json:"risk_id"`
	MeasureID uuid.UUID `json:"measure_id"`
	Note      string    `json:"note"`
}

type RiskReassessmentEvent struct {
	ID            uuid.UUID     `json:"id"`
	RiskID        uuid.UUID     `json:"risk_id"`
	MeasureID     uuid.UUID     `json:"measure_id"`
	TriggerStatus string        `json:"trigger_status"`
	TriggeredAt   time.Time     `json:"triggered_at"`
	TriggeredBy   uuid.NullUUID `json:"triggered_by"`
	Note          string        `json:"note"`
}

type RiskScaleLabel struct {
	Scale       string `json:"scale"`
	Level       int32  `json:"level"`
	Label       string `json:"label"`
	Description string `json:"description"`
}

type Session struct {
	Token  string        `json:"token"`
	Data   []byte        `json:"data"`
	Expiry time.Time     `json:"expiry"`
	UserID uuid.NullUUID `json:"user_id"`
}

type User struct {
	ID         uuid.UUID     `json:"id"`
	Provider   string        `json:"provider"`
	ProviderID string        `json:"provider_id"`
	Email      string        `json:"email"`
	Name       string        `json:"name"`
	Role       string        `json:"role"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
	OrgID      uuid.NullUUID `json:"org_id"`
}
