// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO resource_participants (resource_type, resource_id, user_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (resource_type, resource_id, user_id) DO NOTHING
`

type AddParticipantParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	UserID       uuid.UUID `json:"user_id"`
	Role         string    `json:"role"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addParticipant,
		arg.ResourceType,
		arg.ResourceID,
		arg.UserID,
		arg.Role,
	)
	return err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS(
    SELECT 1 FROM resource_participants
    WHERE resource_type = $1 AND resource_id = $2 AND user_id = $3
) AS is_participant
`

type IsParticipantParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isParticipant, arg.ResourceType, arg.ResourceID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}
