// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: risks.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const acceptAssessment = `-- name: AcceptAssessment :one
UPDATE risk_assessments
SET status = 'active', acceptance_note = '', updated_at = NOW()
WHERE id = $1
RETURNING id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow
`

func (q *Queries) AcceptAssessment(ctx context.Context, id uuid.UUID) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, acceptAssessment, id)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.AnalysisObject,
		&i.SecurityObjectives,
		&i.BusinessObjectives,
		&i.Type,
		&i.Status,
		&i.CurrentStep,
		&i.LastReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RiskOwnerID,
		&i.OrgID,
		&i.RefNum,
		&i.AcceptanceNote,
		&i.IsPublic,
		&i.ThreatAssessmentEnabled,
		&i.ThreatAppDescription,
		&i.ThreatInformationFlow,
	)
	return i, err
}

const addAssessmentParticipant = `-- name: AddAssessmentParticipant :exec
INSERT INTO risk_assessment_participants (assessment_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddAssessmentParticipantParams struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) AddAssessmentParticipant(ctx context.Context, arg AddAssessmentParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addAssessmentParticipant, arg.AssessmentID, arg.UserID)
	return err
}

const clearAssessmentParticipants = `-- name: ClearAssessmentParticipants :exec
DELETE FROM risk_assessment_participants WHERE assessment_id = $1
`

func (q *Queries) ClearAssessmentParticipants(ctx context.Context, assessmentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearAssessmentParticipants, assessmentID)
	return err
}

const clearRiskAssets = `-- name: ClearRiskAssets :exec
DELETE FROM risk_asset_links WHERE risk_id = $1
`

func (q *Queries) ClearRiskAssets(ctx context.Context, riskID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearRiskAssets, riskID)
	return err
}

const countRisksForMatrix = `-- name: CountRisksForMatrix :many
SELECT likelihood_current, consequence_current, COUNT(*) AS count
FROM risks
WHERE likelihood_current IS NOT NULL AND consequence_current IS NOT NULL
GROUP BY likelihood_current, consequence_current
`

type CountRisksForMatrixRow struct {
	LikelihoodCurrent  sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent sql.NullInt32 `json:"consequence_current"`
	Count              int64         `json:"count"`
}

func (q *Queries) CountRisksForMatrix(ctx context.Context) ([]CountRisksForMatrixRow, error) {
	rows, err := q.db.QueryContext(ctx, countRisksForMatrix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRisksForMatrixRow
	for rows.Next() {
		var i CountRisksForMatrixRow
		if err := rows.Scan(&i.LikelihoodCurrent, &i.ConsequenceCurrent, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRisk = `-- name: CreateRisk :one
INSERT INTO risks (assessment_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, assessment_id, name, likelihood_current, consequence_current, likelihood_target, consequence_target, risk_decision, status, created_at, updated_at, description, likelihood_reasoning, consequence_reasoning, owner_id, decision_notes, ref_num, review_needed, review_due, assessed_at, assessed_by, assessment_rationale
`

type CreateRiskParams struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
}

func (q *Queries) CreateRisk(ctx context.Context, arg CreateRiskParams) (Risk, error) {
	row := q.db.QueryRowContext(ctx, createRisk, arg.AssessmentID, arg.Name, arg.Description)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Name,
		&i.LikelihoodCurrent,
		&i.ConsequenceCurrent,
		&i.LikelihoodTarget,
		&i.ConsequenceTarget,
		&i.RiskDecision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LikelihoodReasoning,
		&i.ConsequenceReasoning,
		&i.OwnerID,
		&i.DecisionNotes,
		&i.RefNum,
		&i.ReviewNeeded,
		&i.ReviewDue,
		&i.AssessedAt,
		&i.AssessedBy,
		&i.AssessmentRationale,
	)
	return i, err
}

const createRiskAssessment = `-- name: CreateRiskAssessment :one
INSERT INTO risk_assessments (
    name, scope, analysis_object, security_objectives, business_objectives,
    type, risk_owner_id, org_id, created_by, threat_assessment_enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow
`

type CreateRiskAssessmentParams struct {
	Name                    string        `json:"name"`
	Scope                   string        `json:"scope"`
	AnalysisObject          string        `json:"analysis_object"`
	SecurityObjectives      string        `json:"security_objectives"`
	BusinessObjectives      string        `json:"business_objectives"`
	Type                    string        `json:"type"`
	RiskOwnerID             uuid.NullUUID `json:"risk_owner_id"`
	OrgID                   uuid.NullUUID `json:"org_id"`
	CreatedBy               uuid.NullUUID `json:"created_by"`
	ThreatAssessmentEnabled bool          `json:"threat_assessment_enabled"`
}

func (q *Queries) CreateRiskAssessment(ctx context.Context, arg CreateRiskAssessmentParams) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, createRiskAssessment,
		arg.Name,
		arg.Scope,
		arg.AnalysisObject,
		arg.SecurityObjectives,
		arg.BusinessObjectives,
		arg.Type,
		arg.RiskOwnerID,
		arg.OrgID,
		arg.CreatedBy,
		arg.ThreatAssessmentEnabled,
	)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.AnalysisObject,
		&i.SecurityObjectives,
		&i.BusinessObjectives,
		&i.Type,
		&i.Status,
		&i.CurrentStep,
		&i.LastReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RiskOwnerID,
		&i.OrgID,
		&i.RefNum,
		&i.AcceptanceNote,
		&i.IsPublic,
		&i.ThreatAssessmentEnabled,
		&i.ThreatAppDescription,
		&i.ThreatInformationFlow,
	)
	return i, err
}

const createRiskReassessmentEvent = `-- name: CreateRiskReassessmentEvent :exec
INSERT INTO risk_reassessment_events (risk_id, measure_id, trigger_status, triggered_by, note)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRiskReassessmentEventParams struct {
	RiskID        uuid.UUID     `json:"risk_id"`
	MeasureID     uuid.UUID     `json:"measure_id"`
	TriggerStatus string        `json:"trigger_status"`
	TriggeredBy   uuid.NullUUID `json:"triggered_by"`
	Note          string        `json:"note"`
}

func (q *Queries) CreateRiskReassessmentEvent(ctx context.Context, arg CreateRiskReassessmentEventParams) error {
	_, err := q.db.ExecContext(ctx, createRiskReassessmentEvent,
		arg.RiskID,
		arg.MeasureID,
		arg.TriggerStatus,
		arg.TriggeredBy,
		arg.Note,
	)
	return err
}

const declineAssessment = `-- name: DeclineAssessment :one
UPDATE risk_assessments
SET status = 'draft', acceptance_note = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow
`

type DeclineAssessmentParams struct {
	ID             uuid.UUID `json:"id"`
	AcceptanceNote string    `json:"acceptance_note"`
}

func (q *Queries) DeclineAssessment(ctx context.Context, arg DeclineAssessmentParams) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, declineAssessment, arg.ID, arg.AcceptanceNote)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.AnalysisObject,
		&i.SecurityObjectives,
		&i.BusinessObjectives,
		&i.Type,
		&i.Status,
		&i.CurrentStep,
		&i.LastReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RiskOwnerID,
		&i.OrgID,
		&i.RefNum,
		&i.AcceptanceNote,
		&i.IsPublic,
		&i.ThreatAssessmentEnabled,
		&i.ThreatAppDescription,
		&i.ThreatInformationFlow,
	)
	return i, err
}

const deleteRisk = `-- name: DeleteRisk :exec
DELETE FROM risks WHERE id = $1
`

func (q *Queries) DeleteRisk(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRisk, id)
	return err
}

const deleteRiskAssessment = `-- name: DeleteRiskAssessment :exec
DELETE FROM risk_assessments WHERE id = $1
`

func (q *Queries) DeleteRiskAssessment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRiskAssessment, id)
	return err
}

const filterAllRisks = `-- name: FilterAllRisks :many
SELECT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale, ra.name AS assessment_name, ra.ref_num AS assessment_ref_num
FROM risks r
JOIN risk_assessments ra ON ra.id = r.assessment_id
WHERE ($1 = '' OR r.name ILIKE '%' || $1 || '%' OR r.description ILIKE '%' || $1 || '%' OR ra.name ILIKE '%' || $1 || '%')
ORDER BY COALESCE(r.likelihood_current, 0) * COALESCE(r.consequence_current, 0) DESC, r.created_at DESC
`

type FilterAllRisksRow struct {
	ID                   uuid.UUID     `json:"id"`
	AssessmentID         uuid.UUID     `json:"assessment_id"`
	Name                 string        `json:"name"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodTarget     sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget    sql.NullInt32 `json:"consequence_target"`
	RiskDecision         string        `json:"risk_decision"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	Description          string        `json:"description"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
	OwnerID              uuid.NullUUID `json:"owner_id"`
	DecisionNotes        string        `json:"decision_notes"`
	RefNum               sql.NullInt32 `json:"ref_num"`
	ReviewNeeded         bool          `json:"review_needed"`
	ReviewDue            sql.NullTime  `json:"review_due"`
	AssessedAt           sql.NullTime  `json:"assessed_at"`
	AssessedBy           uuid.NullUUID `json:"assessed_by"`
	AssessmentRationale  string        `json:"assessment_rationale"`
	AssessmentName       string        `json:"assessment_name"`
	AssessmentRefNum     sql.NullInt32 `json:"assessment_ref_num"`
}

func (q *Queries) FilterAllRisks(ctx context.Context, q_ interface{}) ([]FilterAllRisksRow, error) {
	rows, err := q.db.QueryContext(ctx, filterAllRisks, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterAllRisksRow
	for rows.Next() {
		var i FilterAllRisksRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
			&i.AssessmentName,
			&i.AssessmentRefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterAllRisksForUser = `-- name: FilterAllRisksForUser :many
SELECT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale, ra.name AS assessment_name, ra.ref_num AS assessment_ref_num
FROM risks r
JOIN risk_assessments ra ON ra.id = r.assessment_id
WHERE (ra.is_public = true OR ra.risk_owner_id = $1::uuid OR ra.created_by = $1::uuid OR EXISTS (
    SELECT 1 FROM risk_assessment_participants rap WHERE rap.assessment_id = ra.id AND rap.user_id = $1::uuid
))
  AND ($2 = '' OR r.name ILIKE '%' || $2 || '%' OR r.description ILIKE '%' || $2 || '%')
ORDER BY COALESCE(r.likelihood_current, 0) * COALESCE(r.consequence_current, 0) DESC, r.created_at DESC
`

type FilterAllRisksForUserParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Q      interface{} `json:"q"`
}

type FilterAllRisksForUserRow struct {
	ID                   uuid.UUID     `json:"id"`
	AssessmentID         uuid.UUID     `json:"assessment_id"`
	Name                 string        `json:"name"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodTarget     sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget    sql.NullInt32 `json:"consequence_target"`
	RiskDecision         string        `json:"risk_decision"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	Description          string        `json:"description"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
	OwnerID              uuid.NullUUID `json:"owner_id"`
	DecisionNotes        string        `json:"decision_notes"`
	RefNum               sql.NullInt32 `json:"ref_num"`
	ReviewNeeded         bool          `json:"review_needed"`
	ReviewDue            sql.NullTime  `json:"review_due"`
	AssessedAt           sql.NullTime  `json:"assessed_at"`
	AssessedBy           uuid.NullUUID `json:"assessed_by"`
	AssessmentRationale  string        `json:"assessment_rationale"`
	AssessmentName       string        `json:"assessment_name"`
	AssessmentRefNum     sql.NullInt32 `json:"assessment_ref_num"`
}

func (q *Queries) FilterAllRisksForUser(ctx context.Context, arg FilterAllRisksForUserParams) ([]FilterAllRisksForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, filterAllRisksForUser, arg.UserID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterAllRisksForUserRow
	for rows.Next() {
		var i FilterAllRisksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
			&i.AssessmentName,
			&i.AssessmentRefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterRiskAssessments = `-- name: FilterRiskAssessments :many
SELECT id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow FROM risk_assessments
WHERE ($1 = '' OR name ILIKE '%' || $1 || '%' OR scope ILIKE '%' || $1 || '%')
ORDER BY updated_at DESC
`

func (q *Queries) FilterRiskAssessments(ctx context.Context, q_ interface{}) ([]RiskAssessment, error) {
	rows, err := q.db.QueryContext(ctx, filterRiskAssessments, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskAssessment
	for rows.Next() {
		var i RiskAssessment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.AnalysisObject,
			&i.SecurityObjectives,
			&i.BusinessObjectives,
			&i.Type,
			&i.Status,
			&i.CurrentStep,
			&i.LastReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RiskOwnerID,
			&i.OrgID,
			&i.RefNum,
			&i.AcceptanceNote,
			&i.IsPublic,
			&i.ThreatAssessmentEnabled,
			&i.ThreatAppDescription,
			&i.ThreatInformationFlow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterRiskAssessmentsForUser = `-- name: FilterRiskAssessmentsForUser :many
SELECT DISTINCT ra.id, ra.name, ra.scope, ra.analysis_object, ra.security_objectives, ra.business_objectives, ra.type, ra.status, ra.current_step, ra.last_reviewed_at, ra.created_by, ra.created_at, ra.updated_at, ra.risk_owner_id, ra.org_id, ra.ref_num, ra.acceptance_note, ra.is_public, ra.threat_assessment_enabled, ra.threat_app_description, ra.threat_information_flow
FROM risk_assessments ra
LEFT JOIN risk_assessment_participants rap ON rap.assessment_id = ra.id
WHERE (ra.is_public = true OR ra.risk_owner_id = $1::uuid OR ra.created_by = $1::uuid OR rap.user_id = $1::uuid)
  AND ($2 = '' OR ra.name ILIKE '%' || $2 || '%' OR ra.scope ILIKE '%' || $2 || '%')
ORDER BY ra.updated_at DESC
`

type FilterRiskAssessmentsForUserParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Q      interface{} `json:"q"`
}

func (q *Queries) FilterRiskAssessmentsForUser(ctx context.Context, arg FilterRiskAssessmentsForUserParams) ([]RiskAssessment, error) {
	rows, err := q.db.QueryContext(ctx, filterRiskAssessmentsForUser, arg.UserID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskAssessment
	for rows.Next() {
		var i RiskAssessment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.AnalysisObject,
			&i.SecurityObjectives,
			&i.BusinessObjectives,
			&i.Type,
			&i.Status,
			&i.CurrentStep,
			&i.LastReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RiskOwnerID,
			&i.OrgID,
			&i.RefNum,
			&i.AcceptanceNote,
			&i.IsPublic,
			&i.ThreatAssessmentEnabled,
			&i.ThreatAppDescription,
			&i.ThreatInformationFlow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flagRiskForReview = `-- name: FlagRiskForReview :exec
UPDATE risks
SET review_needed = TRUE,
    review_due = COALESCE(review_due, NOW()),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) FlagRiskForReview(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, flagRiskForReview, id)
	return err
}

const getRisk = `-- name: GetRisk :one
SELECT id, assessment_id, name, likelihood_current, consequence_current, likelihood_target, consequence_target, risk_decision, status, created_at, updated_at, description, likelihood_reasoning, consequence_reasoning, owner_id, decision_notes, ref_num, review_needed, review_due, assessed_at, assessed_by, assessment_rationale FROM risks WHERE id = $1
`

func (q *Queries) GetRisk(ctx context.Context, id uuid.UUID) (Risk, error) {
	row := q.db.QueryRowContext(ctx, getRisk, id)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Name,
		&i.LikelihoodCurrent,
		&i.ConsequenceCurrent,
		&i.LikelihoodTarget,
		&i.ConsequenceTarget,
		&i.RiskDecision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LikelihoodReasoning,
		&i.ConsequenceReasoning,
		&i.OwnerID,
		&i.DecisionNotes,
		&i.RefNum,
		&i.ReviewNeeded,
		&i.ReviewDue,
		&i.AssessedAt,
		&i.AssessedBy,
		&i.AssessmentRationale,
	)
	return i, err
}

const getRiskAssessment = `-- name: GetRiskAssessment :one
SELECT id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow FROM risk_assessments WHERE id = $1
`

func (q *Queries) GetRiskAssessment(ctx context.Context, id uuid.UUID) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, getRiskAssessment, id)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.AnalysisObject,
		&i.SecurityObjectives,
		&i.BusinessObjectives,
		&i.Type,
		&i.Status,
		&i.CurrentStep,
		&i.LastReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RiskOwnerID,
		&i.OrgID,
		&i.RefNum,
		&i.AcceptanceNote,
		&i.IsPublic,
		&i.ThreatAssessmentEnabled,
		&i.ThreatAppDescription,
		&i.ThreatInformationFlow,
	)
	return i, err
}

const getRiskGlobalSettings = `-- name: GetRiskGlobalSettings :one
SELECT id, acceptance_criteria, low_max, high_min FROM risk_global_settings WHERE id = 1
`

func (q *Queries) GetRiskGlobalSettings(ctx context.Context) (RiskGlobalSetting, error) {
	row := q.db.QueryRowContext(ctx, getRiskGlobalSettings)
	var i RiskGlobalSetting
	err := row.Scan(
		&i.ID,
		&i.AcceptanceCriteria,
		&i.LowMax,
		&i.HighMin,
	)
	return i, err
}

const getRiskStats = `-- name: GetRiskStats :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE likelihood_current * consequence_current >= 12) AS red_count,
    COUNT(*) FILTER (WHERE likelihood_current * consequence_current BETWEEN 6 AND 11) AS yellow_count,
    COUNT(*) FILTER (WHERE likelihood_current * consequence_current BETWEEN 1 AND 5) AS green_count
FROM risks
WHERE likelihood_current IS NOT NULL AND consequence_current IS NOT NULL
`

type GetRiskStatsRow struct {
	Total       int64 `json:"total"`
	RedCount    int64 `json:"red_count"`
	YellowCount int64 `json:"yellow_count"`
	GreenCount  int64 `json:"green_count"`
}

func (q *Queries) GetRiskStats(ctx context.Context) (GetRiskStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getRiskStats)
	var i GetRiskStatsRow
	err := row.Scan(
		&i.Total,
		&i.RedCount,
		&i.YellowCount,
		&i.GreenCount,
	)
	return i, err
}

const isRiskAssessmentAccessible = `-- name: IsRiskAssessmentAccessible :one
SELECT EXISTS(
    SELECT 1 FROM risk_assessments ra
    LEFT JOIN risk_assessment_participants rap ON rap.assessment_id = ra.id
    WHERE ra.id = $1
    AND (ra.is_public = true OR ra.risk_owner_id = $2::uuid OR ra.created_by = $2::uuid OR rap.user_id = $2::uuid)
) AS accessible
`

type IsRiskAssessmentAccessibleParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) IsRiskAssessmentAccessible(ctx context.Context, arg IsRiskAssessmentAccessibleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRiskAssessmentAccessible, arg.ID, arg.Column2)
	var accessible bool
	err := row.Scan(&accessible)
	return accessible, err
}

const isRiskAssessmentParticipant = `-- name: IsRiskAssessmentParticipant :one
SELECT EXISTS(
    SELECT 1
    FROM risk_assessment_participants
    WHERE assessment_id = $1 AND user_id = $2
) AS is_participant
`

type IsRiskAssessmentParticipantParams struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) IsRiskAssessmentParticipant(ctx context.Context, arg IsRiskAssessmentParticipantParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRiskAssessmentParticipant, arg.AssessmentID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}

const linkRiskToActivity = `-- name: LinkRiskToActivity :exec
INSERT INTO risk_activity_links (risk_id, activity_id)
VALUES ($1, $2)
ON CONFLICT (risk_id, activity_id) DO NOTHING
`

type LinkRiskToActivityParams struct {
	RiskID     uuid.UUID `json:"risk_id"`
	ActivityID uuid.UUID `json:"activity_id"`
}

func (q *Queries) LinkRiskToActivity(ctx context.Context, arg LinkRiskToActivityParams) error {
	_, err := q.db.ExecContext(ctx, linkRiskToActivity, arg.RiskID, arg.ActivityID)
	return err
}

const linkRiskToAsset = `-- name: LinkRiskToAsset :exec
INSERT INTO risk_asset_links (risk_id, asset_id)
VALUES ($1, $2)
ON CONFLICT (risk_id, asset_id) DO NOTHING
`

type LinkRiskToAssetParams struct {
	RiskID  uuid.UUID `json:"risk_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

func (q *Queries) LinkRiskToAsset(ctx context.Context, arg LinkRiskToAssetParams) error {
	_, err := q.db.ExecContext(ctx, linkRiskToAsset, arg.RiskID, arg.AssetID)
	return err
}

const linkRiskToMeasure = `-- name: LinkRiskToMeasure :exec
INSERT INTO risk_measure_links (risk_id, measure_id, note)
VALUES ($1, $2, $3)
ON CONFLICT (risk_id, measure_id) DO NOTHING
`

type LinkRiskToMeasureParams struct {
	RiskID    uuid.UUID `json:"risk_id"`
	MeasureID uuid.UUID `json:"measure_id"`
	Note      string    `json:"note"`
}

func (q *Queries) LinkRiskToMeasure(ctx context.Context, arg LinkRiskToMeasureParams) error {
	_, err := q.db.ExecContext(ctx, linkRiskToMeasure, arg.RiskID, arg.MeasureID, arg.Note)
	return err
}

const listActivitiesForRisk = `-- name: ListActivitiesForRisk :many
SELECT a.id, a.measure_id, a.title, a.description, a.activity_type, a.recurrence, a.status, a.owner, a.due_date, a.completed_at, a.completed_by, a.notes, a.evidence_url, a.parent_activity_id, a.created_at, a.updated_at, a.assignee_id, a.priority, a.kind, a.ref_num FROM activities a
JOIN risk_activity_links ral ON ral.activity_id = a.id
WHERE ral.risk_id = $1
ORDER BY a.title
`

func (q *Queries) ListActivitiesForRisk(ctx context.Context, riskID uuid.UUID) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesForRisk, riskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.MeasureID,
			&i.Title,
			&i.Description,
			&i.ActivityType,
			&i.Recurrence,
			&i.Status,
			&i.Owner,
			&i.DueDate,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.Notes,
			&i.EvidenceUrl,
			&i.ParentActivityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneeID,
			&i.Priority,
			&i.Kind,
			&i.RefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRisks = `-- name: ListAllRisks :many
SELECT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale, ra.name AS assessment_name, ra.ref_num AS assessment_ref_num
FROM risks r
JOIN risk_assessments ra ON ra.id = r.assessment_id
ORDER BY COALESCE(r.likelihood_current, 0) * COALESCE(r.consequence_current, 0) DESC, r.created_at DESC
`

type ListAllRisksRow struct {
	ID                   uuid.UUID     `json:"id"`
	AssessmentID         uuid.UUID     `json:"assessment_id"`
	Name                 string        `json:"name"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodTarget     sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget    sql.NullInt32 `json:"consequence_target"`
	RiskDecision         string        `json:"risk_decision"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	Description          string        `json:"description"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
	OwnerID              uuid.NullUUID `json:"owner_id"`
	DecisionNotes        string        `json:"decision_notes"`
	RefNum               sql.NullInt32 `json:"ref_num"`
	ReviewNeeded         bool          `json:"review_needed"`
	ReviewDue            sql.NullTime  `json:"review_due"`
	AssessedAt           sql.NullTime  `json:"assessed_at"`
	AssessedBy           uuid.NullUUID `json:"assessed_by"`
	AssessmentRationale  string        `json:"assessment_rationale"`
	AssessmentName       string        `json:"assessment_name"`
	AssessmentRefNum     sql.NullInt32 `json:"assessment_ref_num"`
}

func (q *Queries) ListAllRisks(ctx context.Context) ([]ListAllRisksRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRisks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRisksRow
	for rows.Next() {
		var i ListAllRisksRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
			&i.AssessmentName,
			&i.AssessmentRefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRisksForUser = `-- name: ListAllRisksForUser :many
SELECT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale, ra.name AS assessment_name, ra.ref_num AS assessment_ref_num
FROM risks r
JOIN risk_assessments ra ON ra.id = r.assessment_id
WHERE ra.is_public = true
   OR ra.risk_owner_id = $1::uuid
   OR ra.created_by = $1::uuid
   OR EXISTS (
       SELECT 1 FROM risk_assessment_participants rap
       WHERE rap.assessment_id = ra.id AND rap.user_id = $1::uuid
   )
ORDER BY COALESCE(r.likelihood_current, 0) * COALESCE(r.consequence_current, 0) DESC, r.created_at DESC
`

type ListAllRisksForUserRow struct {
	ID                   uuid.UUID     `json:"id"`
	AssessmentID         uuid.UUID     `json:"assessment_id"`
	Name                 string        `json:"name"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodTarget     sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget    sql.NullInt32 `json:"consequence_target"`
	RiskDecision         string        `json:"risk_decision"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	Description          string        `json:"description"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
	OwnerID              uuid.NullUUID `json:"owner_id"`
	DecisionNotes        string        `json:"decision_notes"`
	RefNum               sql.NullInt32 `json:"ref_num"`
	ReviewNeeded         bool          `json:"review_needed"`
	ReviewDue            sql.NullTime  `json:"review_due"`
	AssessedAt           sql.NullTime  `json:"assessed_at"`
	AssessedBy           uuid.NullUUID `json:"assessed_by"`
	AssessmentRationale  string        `json:"assessment_rationale"`
	AssessmentName       string        `json:"assessment_name"`
	AssessmentRefNum     sql.NullInt32 `json:"assessment_ref_num"`
}

func (q *Queries) ListAllRisksForUser(ctx context.Context, dollar_1 uuid.UUID) ([]ListAllRisksForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRisksForUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRisksForUserRow
	for rows.Next() {
		var i ListAllRisksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
			&i.AssessmentName,
			&i.AssessmentRefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsForRisk = `-- name: ListAssetsForRisk :many
SELECT a.id, a.name, a.description, a.asset_type, a.owner, a.status, a.criticality, a.created_at, a.updated_at
FROM assets a
JOIN risk_asset_links ral ON ral.asset_id = a.id
WHERE ral.risk_id = $1
ORDER BY a.name
`

func (q *Queries) ListAssetsForRisk(ctx context.Context, riskID uuid.UUID) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsForRisk, riskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AssetType,
			&i.Owner,
			&i.Status,
			&i.Criticality,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasureRiskLinkIDs = `-- name: ListMeasureRiskLinkIDs :many
SELECT DISTINCT measure_id FROM risk_measure_links ORDER BY measure_id
`

func (q *Queries) ListMeasureRiskLinkIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listMeasureRiskLinkIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var measure_id uuid.UUID
		if err := rows.Scan(&measure_id); err != nil {
			return nil, err
		}
		items = append(items, measure_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasuresForRisk = `-- name: ListMeasuresForRisk :many
SELECT m.id, m.name, m.description, m.category, m.owner, m.status, m.created_at, m.updated_at, m.last_verified_at, m.assignee_id, m.ref_num FROM measures m
JOIN risk_measure_links rml ON rml.measure_id = m.id
WHERE rml.risk_id = $1
ORDER BY m.name
`

func (q *Queries) ListMeasuresForRisk(ctx context.Context, riskID uuid.UUID) ([]Measure, error) {
	rows, err := q.db.QueryContext(ctx, listMeasuresForRisk, riskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measure
	for rows.Next() {
		var i Measure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Owner,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastVerifiedAt,
			&i.AssigneeID,
			&i.RefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedRisks = `-- name: ListOwnedRisks :many
SELECT
    r.id,
    r.assessment_id,
    r.name,
    COALESCE(r.likelihood_current, 0) AS likelihood_current,
    COALESCE(r.consequence_current, 0) AS consequence_current,
    to_char(r.updated_at, 'YYYY-MM-DD HH24:MI') AS updated_at,
    ra.name AS assessment_name,
    COALESCE(ra.ref_num, 0) AS assessment_ref_num
FROM risks r
JOIN risk_assessments ra ON ra.id = r.assessment_id
WHERE r.owner_id = $1
ORDER BY r.updated_at DESC
LIMIT 25
`

type ListOwnedRisksRow struct {
	ID                 uuid.UUID `json:"id"`
	AssessmentID       uuid.UUID `json:"assessment_id"`
	Name               string    `json:"name"`
	LikelihoodCurrent  int32     `json:"likelihood_current"`
	ConsequenceCurrent int32     `json:"consequence_current"`
	UpdatedAt          string    `json:"updated_at"`
	AssessmentName     string    `json:"assessment_name"`
	AssessmentRefNum   int32     `json:"assessment_ref_num"`
}

func (q *Queries) ListOwnedRisks(ctx context.Context, ownerID uuid.NullUUID) ([]ListOwnedRisksRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnedRisks, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnedRisksRow
	for rows.Next() {
		var i ListOwnedRisksRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.UpdatedAt,
			&i.AssessmentName,
			&i.AssessmentRefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsForAssessment = `-- name: ListParticipantsForAssessment :many
SELECT u.id, u.provider, u.provider_id, u.email, u.name, u.role, u.created_at, u.updated_at, u.org_id
FROM users u
JOIN risk_assessment_participants rap ON rap.user_id = u.id
WHERE rap.assessment_id = $1
ORDER BY u.name
`

func (q *Queries) ListParticipantsForAssessment(ctx context.Context, assessmentID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantsForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskAssessments = `-- name: ListRiskAssessments :many
SELECT id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow FROM risk_assessments ORDER BY updated_at DESC
`

func (q *Queries) ListRiskAssessments(ctx context.Context) ([]RiskAssessment, error) {
	rows, err := q.db.QueryContext(ctx, listRiskAssessments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskAssessment
	for rows.Next() {
		var i RiskAssessment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.AnalysisObject,
			&i.SecurityObjectives,
			&i.BusinessObjectives,
			&i.Type,
			&i.Status,
			&i.CurrentStep,
			&i.LastReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RiskOwnerID,
			&i.OrgID,
			&i.RefNum,
			&i.AcceptanceNote,
			&i.IsPublic,
			&i.ThreatAssessmentEnabled,
			&i.ThreatAppDescription,
			&i.ThreatInformationFlow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskAssessmentsForUser = `-- name: ListRiskAssessmentsForUser :many
SELECT DISTINCT ra.id, ra.name, ra.scope, ra.analysis_object, ra.security_objectives, ra.business_objectives, ra.type, ra.status, ra.current_step, ra.last_reviewed_at, ra.created_by, ra.created_at, ra.updated_at, ra.risk_owner_id, ra.org_id, ra.ref_num, ra.acceptance_note, ra.is_public, ra.threat_assessment_enabled, ra.threat_app_description, ra.threat_information_flow
FROM risk_assessments ra
LEFT JOIN risk_assessment_participants rap ON rap.assessment_id = ra.id
WHERE ra.is_public = true
   OR ra.risk_owner_id = $1
   OR ra.created_by = $1
   OR rap.user_id = $1
ORDER BY ra.updated_at DESC
`

func (q *Queries) ListRiskAssessmentsForUser(ctx context.Context, riskOwnerID uuid.NullUUID) ([]RiskAssessment, error) {
	rows, err := q.db.QueryContext(ctx, listRiskAssessmentsForUser, riskOwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskAssessment
	for rows.Next() {
		var i RiskAssessment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.AnalysisObject,
			&i.SecurityObjectives,
			&i.BusinessObjectives,
			&i.Type,
			&i.Status,
			&i.CurrentStep,
			&i.LastReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RiskOwnerID,
			&i.OrgID,
			&i.RefNum,
			&i.AcceptanceNote,
			&i.IsPublic,
			&i.ThreatAssessmentEnabled,
			&i.ThreatAppDescription,
			&i.ThreatInformationFlow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskReassessmentEvents = `-- name: ListRiskReassessmentEvents :many
SELECT
    rre.id,
    rre.risk_id,
    rre.measure_id,
    rre.trigger_status,
    rre.triggered_at,
    rre.triggered_by,
    rre.note,
    m.name AS measure_name,
    m.ref_num AS measure_ref_num
FROM risk_reassessment_events rre
JOIN measures m ON m.id = rre.measure_id
WHERE rre.risk_id = $1
  AND (
      $2::timestamptz IS NULL
      OR rre.triggered_at > $2::timestamptz
  )
ORDER BY rre.triggered_at DESC
`

type ListRiskReassessmentEventsParams struct {
	RiskID  uuid.UUID    `json:"risk_id"`
	SinceAt sql.NullTime `json:"since_at"`
}

type ListRiskReassessmentEventsRow struct {
	ID            uuid.UUID     `json:"id"`
	RiskID        uuid.UUID     `json:"risk_id"`
	MeasureID     uuid.UUID     `json:"measure_id"`
	TriggerStatus string        `json:"trigger_status"`
	TriggeredAt   time.Time     `json:"triggered_at"`
	TriggeredBy   uuid.NullUUID `json:"triggered_by"`
	Note          string        `json:"note"`
	MeasureName   string        `json:"measure_name"`
	MeasureRefNum sql.NullInt32 `json:"measure_ref_num"`
}

func (q *Queries) ListRiskReassessmentEvents(ctx context.Context, arg ListRiskReassessmentEventsParams) ([]ListRiskReassessmentEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRiskReassessmentEvents, arg.RiskID, arg.SinceAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiskReassessmentEventsRow
	for rows.Next() {
		var i ListRiskReassessmentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RiskID,
			&i.MeasureID,
			&i.TriggerStatus,
			&i.TriggeredAt,
			&i.TriggeredBy,
			&i.Note,
			&i.MeasureName,
			&i.MeasureRefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskReviewQueue = `-- name: ListRiskReviewQueue :many
SELECT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale, ra.name AS assessment_name, ra.ref_num AS assessment_ref_num
FROM risks r
JOIN risk_assessments ra ON ra.id = r.assessment_id
WHERE r.review_needed = TRUE
ORDER BY COALESCE(r.review_due, r.updated_at) ASC, r.updated_at DESC
`

type ListRiskReviewQueueRow struct {
	ID                   uuid.UUID     `json:"id"`
	AssessmentID         uuid.UUID     `json:"assessment_id"`
	Name                 string        `json:"name"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodTarget     sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget    sql.NullInt32 `json:"consequence_target"`
	RiskDecision         string        `json:"risk_decision"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	Description          string        `json:"description"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
	OwnerID              uuid.NullUUID `json:"owner_id"`
	DecisionNotes        string        `json:"decision_notes"`
	RefNum               sql.NullInt32 `json:"ref_num"`
	ReviewNeeded         bool          `json:"review_needed"`
	ReviewDue            sql.NullTime  `json:"review_due"`
	AssessedAt           sql.NullTime  `json:"assessed_at"`
	AssessedBy           uuid.NullUUID `json:"assessed_by"`
	AssessmentRationale  string        `json:"assessment_rationale"`
	AssessmentName       string        `json:"assessment_name"`
	AssessmentRefNum     sql.NullInt32 `json:"assessment_ref_num"`
}

func (q *Queries) ListRiskReviewQueue(ctx context.Context) ([]ListRiskReviewQueueRow, error) {
	rows, err := q.db.QueryContext(ctx, listRiskReviewQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiskReviewQueueRow
	for rows.Next() {
		var i ListRiskReviewQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
			&i.AssessmentName,
			&i.AssessmentRefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskReviewQueueForUser = `-- name: ListRiskReviewQueueForUser :many
SELECT DISTINCT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale, ra.name AS assessment_name, ra.ref_num AS assessment_ref_num
FROM risks r
JOIN risk_assessments ra ON ra.id = r.assessment_id
LEFT JOIN risk_assessment_participants rap ON rap.assessment_id = ra.id
WHERE r.review_needed = TRUE
  AND (
      ra.is_public = TRUE
      OR ra.risk_owner_id = $1::uuid
      OR ra.created_by = $1::uuid
      OR rap.user_id = $1::uuid
  )
ORDER BY COALESCE(r.review_due, r.updated_at) ASC, r.updated_at DESC
`

type ListRiskReviewQueueForUserRow struct {
	ID                   uuid.UUID     `json:"id"`
	AssessmentID         uuid.UUID     `json:"assessment_id"`
	Name                 string        `json:"name"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodTarget     sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget    sql.NullInt32 `json:"consequence_target"`
	RiskDecision         string        `json:"risk_decision"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	Description          string        `json:"description"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
	OwnerID              uuid.NullUUID `json:"owner_id"`
	DecisionNotes        string        `json:"decision_notes"`
	RefNum               sql.NullInt32 `json:"ref_num"`
	ReviewNeeded         bool          `json:"review_needed"`
	ReviewDue            sql.NullTime  `json:"review_due"`
	AssessedAt           sql.NullTime  `json:"assessed_at"`
	AssessedBy           uuid.NullUUID `json:"assessed_by"`
	AssessmentRationale  string        `json:"assessment_rationale"`
	AssessmentName       string        `json:"assessment_name"`
	AssessmentRefNum     sql.NullInt32 `json:"assessment_ref_num"`
}

func (q *Queries) ListRiskReviewQueueForUser(ctx context.Context, dollar_1 uuid.UUID) ([]ListRiskReviewQueueForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRiskReviewQueueForUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiskReviewQueueForUserRow
	for rows.Next() {
		var i ListRiskReviewQueueForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
			&i.AssessmentName,
			&i.AssessmentRefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskScaleLabels = `-- name: ListRiskScaleLabels :many
SELECT scale, level, label, description FROM risk_scale_labels ORDER BY scale DESC, level ASC
`

func (q *Queries) ListRiskScaleLabels(ctx context.Context) ([]RiskScaleLabel, error) {
	rows, err := q.db.QueryContext(ctx, listRiskScaleLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskScaleLabel
	for rows.Next() {
		var i RiskScaleLabel
		if err := rows.Scan(
			&i.Scale,
			&i.Level,
			&i.Label,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRisksForActivity = `-- name: ListRisksForActivity :many
SELECT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale FROM risks r
JOIN risk_activity_links ral ON ral.risk_id = r.id
WHERE ral.activity_id = $1
ORDER BY r.name
`

func (q *Queries) ListRisksForActivity(ctx context.Context, activityID uuid.UUID) ([]Risk, error) {
	rows, err := q.db.QueryContext(ctx, listRisksForActivity, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Risk
	for rows.Next() {
		var i Risk
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRisksForAssessment = `-- name: ListRisksForAssessment :many
SELECT id, assessment_id, name, likelihood_current, consequence_current, likelihood_target, consequence_target, risk_decision, status, created_at, updated_at, description, likelihood_reasoning, consequence_reasoning, owner_id, decision_notes, ref_num, review_needed, review_due, assessed_at, assessed_by, assessment_rationale FROM risks
WHERE assessment_id = $1
ORDER BY COALESCE(likelihood_current, 0) * COALESCE(consequence_current, 0) DESC, created_at DESC
`

func (q *Queries) ListRisksForAssessment(ctx context.Context, assessmentID uuid.UUID) ([]Risk, error) {
	rows, err := q.db.QueryContext(ctx, listRisksForAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Risk
	for rows.Next() {
		var i Risk
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRisksForMeasure = `-- name: ListRisksForMeasure :many
SELECT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale FROM risks r
JOIN risk_measure_links rml ON rml.risk_id = r.id
WHERE rml.measure_id = $1
ORDER BY r.name
`

func (q *Queries) ListRisksForMeasure(ctx context.Context, measureID uuid.UUID) ([]Risk, error) {
	rows, err := q.db.QueryContext(ctx, listRisksForMeasure, measureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Risk
	for rows.Next() {
		var i Risk
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopRisks = `-- name: ListTopRisks :many
SELECT r.id, r.assessment_id, r.name, r.likelihood_current, r.consequence_current, r.likelihood_target, r.consequence_target, r.risk_decision, r.status, r.created_at, r.updated_at, r.description, r.likelihood_reasoning, r.consequence_reasoning, r.owner_id, r.decision_notes, r.ref_num, r.review_needed, r.review_due, r.assessed_at, r.assessed_by, r.assessment_rationale, ra.name AS assessment_name
FROM risks r
JOIN risk_assessments ra ON ra.id = r.assessment_id
WHERE r.likelihood_current IS NOT NULL AND r.consequence_current IS NOT NULL
ORDER BY r.likelihood_current * r.consequence_current DESC
LIMIT 5
`

type ListTopRisksRow struct {
	ID                   uuid.UUID     `json:"id"`
	AssessmentID         uuid.UUID     `json:"assessment_id"`
	Name                 string        `json:"name"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodTarget     sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget    sql.NullInt32 `json:"consequence_target"`
	RiskDecision         string        `json:"risk_decision"`
	Status               string        `json:"status"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	Description          string        `json:"description"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
	OwnerID              uuid.NullUUID `json:"owner_id"`
	DecisionNotes        string        `json:"decision_notes"`
	RefNum               sql.NullInt32 `json:"ref_num"`
	ReviewNeeded         bool          `json:"review_needed"`
	ReviewDue            sql.NullTime  `json:"review_due"`
	AssessedAt           sql.NullTime  `json:"assessed_at"`
	AssessedBy           uuid.NullUUID `json:"assessed_by"`
	AssessmentRationale  string        `json:"assessment_rationale"`
	AssessmentName       string        `json:"assessment_name"`
}

func (q *Queries) ListTopRisks(ctx context.Context) ([]ListTopRisksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopRisks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopRisksRow
	for rows.Next() {
		var i ListTopRisksRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Name,
			&i.LikelihoodCurrent,
			&i.ConsequenceCurrent,
			&i.LikelihoodTarget,
			&i.ConsequenceTarget,
			&i.RiskDecision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LikelihoodReasoning,
			&i.ConsequenceReasoning,
			&i.OwnerID,
			&i.DecisionNotes,
			&i.RefNum,
			&i.ReviewNeeded,
			&i.ReviewDue,
			&i.AssessedAt,
			&i.AssessedBy,
			&i.AssessmentRationale,
			&i.AssessmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassessRiskCurrentScores = `-- name: ReassessRiskCurrentScores :one
UPDATE risks
SET likelihood_current = $2,
    consequence_current = $3,
    assessment_rationale = $4,
    assessed_at = NOW(),
    assessed_by = $5,
    review_needed = FALSE,
    review_due = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, assessment_id, name, likelihood_current, consequence_current, likelihood_target, consequence_target, risk_decision, status, created_at, updated_at, description, likelihood_reasoning, consequence_reasoning, owner_id, decision_notes, ref_num, review_needed, review_due, assessed_at, assessed_by, assessment_rationale
`

type ReassessRiskCurrentScoresParams struct {
	ID                  uuid.UUID     `json:"id"`
	LikelihoodCurrent   sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent  sql.NullInt32 `json:"consequence_current"`
	AssessmentRationale string        `json:"assessment_rationale"`
	AssessedBy          uuid.NullUUID `json:"assessed_by"`
}

func (q *Queries) ReassessRiskCurrentScores(ctx context.Context, arg ReassessRiskCurrentScoresParams) (Risk, error) {
	row := q.db.QueryRowContext(ctx, reassessRiskCurrentScores,
		arg.ID,
		arg.LikelihoodCurrent,
		arg.ConsequenceCurrent,
		arg.AssessmentRationale,
		arg.AssessedBy,
	)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Name,
		&i.LikelihoodCurrent,
		&i.ConsequenceCurrent,
		&i.LikelihoodTarget,
		&i.ConsequenceTarget,
		&i.RiskDecision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LikelihoodReasoning,
		&i.ConsequenceReasoning,
		&i.OwnerID,
		&i.DecisionNotes,
		&i.RefNum,
		&i.ReviewNeeded,
		&i.ReviewDue,
		&i.AssessedAt,
		&i.AssessedBy,
		&i.AssessmentRationale,
	)
	return i, err
}

const removeAssessmentParticipant = `-- name: RemoveAssessmentParticipant :exec
DELETE FROM risk_assessment_participants
WHERE assessment_id = $1 AND user_id = $2
`

type RemoveAssessmentParticipantParams struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveAssessmentParticipant(ctx context.Context, arg RemoveAssessmentParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeAssessmentParticipant, arg.AssessmentID, arg.UserID)
	return err
}

const searchActivities = `-- name: SearchActivities :many
SELECT a.id, a.measure_id, a.title, a.description, a.activity_type, a.recurrence, a.status, a.owner, a.due_date, a.completed_at, a.completed_by, a.notes, a.evidence_url, a.parent_activity_id, a.created_at, a.updated_at, a.assignee_id, a.priority, a.kind, a.ref_num FROM activities a
WHERE a.title ILIKE $1
ORDER BY a.title
LIMIT 10
`

func (q *Queries) SearchActivities(ctx context.Context, title string) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, searchActivities, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.MeasureID,
			&i.Title,
			&i.Description,
			&i.ActivityType,
			&i.Recurrence,
			&i.Status,
			&i.Owner,
			&i.DueDate,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.Notes,
			&i.EvidenceUrl,
			&i.ParentActivityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneeID,
			&i.Priority,
			&i.Kind,
			&i.RefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAssetsForRisk = `-- name: SearchAssetsForRisk :many
SELECT a.id, a.name, a.description, a.asset_type, a.owner, a.status, a.criticality, a.created_at, a.updated_at
FROM assets a
WHERE
    ($1 = '' OR a.name ILIKE '%' || $1 || '%' OR a.owner ILIKE '%' || $1 || '%')
    AND NOT EXISTS (
        SELECT 1 FROM risk_asset_links ral
        WHERE ral.risk_id = $2
          AND ral.asset_id = a.id
    )
ORDER BY a.name
LIMIT $3
`

type SearchAssetsForRiskParams struct {
	Q          interface{} `json:"q"`
	RiskID     uuid.UUID   `json:"risk_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) SearchAssetsForRisk(ctx context.Context, arg SearchAssetsForRiskParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, searchAssetsForRisk, arg.Q, arg.RiskID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AssetType,
			&i.Owner,
			&i.Status,
			&i.Criticality,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMeasures = `-- name: SearchMeasures :many
SELECT id, name, description, category, owner, status, created_at, updated_at, last_verified_at, assignee_id, ref_num FROM measures
WHERE name ILIKE $1
ORDER BY name
LIMIT 10
`

func (q *Queries) SearchMeasures(ctx context.Context, name string) ([]Measure, error) {
	rows, err := q.db.QueryContext(ctx, searchMeasures, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measure
	for rows.Next() {
		var i Measure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Owner,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastVerifiedAt,
			&i.AssigneeID,
			&i.RefNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRiskAssessmentPublic = `-- name: ToggleRiskAssessmentPublic :one
UPDATE risk_assessments
SET is_public = NOT is_public, updated_at = NOW()
WHERE id = $1
RETURNING id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow
`

func (q *Queries) ToggleRiskAssessmentPublic(ctx context.Context, id uuid.UUID) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, toggleRiskAssessmentPublic, id)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.AnalysisObject,
		&i.SecurityObjectives,
		&i.BusinessObjectives,
		&i.Type,
		&i.Status,
		&i.CurrentStep,
		&i.LastReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RiskOwnerID,
		&i.OrgID,
		&i.RefNum,
		&i.AcceptanceNote,
		&i.IsPublic,
		&i.ThreatAssessmentEnabled,
		&i.ThreatAppDescription,
		&i.ThreatInformationFlow,
	)
	return i, err
}

const unlinkRiskFromActivity = `-- name: UnlinkRiskFromActivity :exec
DELETE FROM risk_activity_links WHERE risk_id = $1 AND activity_id = $2
`

type UnlinkRiskFromActivityParams struct {
	RiskID     uuid.UUID `json:"risk_id"`
	ActivityID uuid.UUID `json:"activity_id"`
}

func (q *Queries) UnlinkRiskFromActivity(ctx context.Context, arg UnlinkRiskFromActivityParams) error {
	_, err := q.db.ExecContext(ctx, unlinkRiskFromActivity, arg.RiskID, arg.ActivityID)
	return err
}

const unlinkRiskFromAsset = `-- name: UnlinkRiskFromAsset :exec
DELETE FROM risk_asset_links WHERE risk_id = $1 AND asset_id = $2
`

type UnlinkRiskFromAssetParams struct {
	RiskID  uuid.UUID `json:"risk_id"`
	AssetID uuid.UUID `json:"asset_id"`
}

func (q *Queries) UnlinkRiskFromAsset(ctx context.Context, arg UnlinkRiskFromAssetParams) error {
	_, err := q.db.ExecContext(ctx, unlinkRiskFromAsset, arg.RiskID, arg.AssetID)
	return err
}

const unlinkRiskFromMeasure = `-- name: UnlinkRiskFromMeasure :exec
DELETE FROM risk_measure_links WHERE risk_id = $1 AND measure_id = $2
`

type UnlinkRiskFromMeasureParams struct {
	RiskID    uuid.UUID `json:"risk_id"`
	MeasureID uuid.UUID `json:"measure_id"`
}

func (q *Queries) UnlinkRiskFromMeasure(ctx context.Context, arg UnlinkRiskFromMeasureParams) error {
	_, err := q.db.ExecContext(ctx, unlinkRiskFromMeasure, arg.RiskID, arg.MeasureID)
	return err
}

const updateRiskAssessmentReviewed = `-- name: UpdateRiskAssessmentReviewed :exec
UPDATE risk_assessments
SET last_reviewed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateRiskAssessmentReviewed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateRiskAssessmentReviewed, id)
	return err
}

const updateRiskAssessmentStep = `-- name: UpdateRiskAssessmentStep :exec
UPDATE risk_assessments
SET current_step = $2, status = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateRiskAssessmentStepParams struct {
	ID          uuid.UUID `json:"id"`
	CurrentStep int32     `json:"current_step"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateRiskAssessmentStep(ctx context.Context, arg UpdateRiskAssessmentStepParams) error {
	_, err := q.db.ExecContext(ctx, updateRiskAssessmentStep, arg.ID, arg.CurrentStep, arg.Status)
	return err
}

const updateRiskAssessmentStep1 = `-- name: UpdateRiskAssessmentStep1 :one
UPDATE risk_assessments
SET name = $2, scope = $3, analysis_object = $4, security_objectives = $5,
    business_objectives = $6, type = $7, risk_owner_id = $8, org_id = $9,
    threat_assessment_enabled = $10,
    current_step = GREATEST(current_step, 2), updated_at = NOW()
WHERE id = $1
RETURNING id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow
`

type UpdateRiskAssessmentStep1Params struct {
	ID                      uuid.UUID     `json:"id"`
	Name                    string        `json:"name"`
	Scope                   string        `json:"scope"`
	AnalysisObject          string        `json:"analysis_object"`
	SecurityObjectives      string        `json:"security_objectives"`
	BusinessObjectives      string        `json:"business_objectives"`
	Type                    string        `json:"type"`
	RiskOwnerID             uuid.NullUUID `json:"risk_owner_id"`
	OrgID                   uuid.NullUUID `json:"org_id"`
	ThreatAssessmentEnabled bool          `json:"threat_assessment_enabled"`
}

func (q *Queries) UpdateRiskAssessmentStep1(ctx context.Context, arg UpdateRiskAssessmentStep1Params) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, updateRiskAssessmentStep1,
		arg.ID,
		arg.Name,
		arg.Scope,
		arg.AnalysisObject,
		arg.SecurityObjectives,
		arg.BusinessObjectives,
		arg.Type,
		arg.RiskOwnerID,
		arg.OrgID,
		arg.ThreatAssessmentEnabled,
	)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.AnalysisObject,
		&i.SecurityObjectives,
		&i.BusinessObjectives,
		&i.Type,
		&i.Status,
		&i.CurrentStep,
		&i.LastReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RiskOwnerID,
		&i.OrgID,
		&i.RefNum,
		&i.AcceptanceNote,
		&i.IsPublic,
		&i.ThreatAssessmentEnabled,
		&i.ThreatAppDescription,
		&i.ThreatInformationFlow,
	)
	return i, err
}

const updateRiskAssessmentThreatStep = `-- name: UpdateRiskAssessmentThreatStep :one
UPDATE risk_assessments
SET threat_app_description  = $2,
    threat_information_flow = $3,
    current_step            = GREATEST(current_step, 2),
    updated_at              = NOW()
WHERE id = $1
RETURNING id, name, scope, analysis_object, security_objectives, business_objectives, type, status, current_step, last_reviewed_at, created_by, created_at, updated_at, risk_owner_id, org_id, ref_num, acceptance_note, is_public, threat_assessment_enabled, threat_app_description, threat_information_flow
`

type UpdateRiskAssessmentThreatStepParams struct {
	ID                    uuid.UUID `json:"id"`
	ThreatAppDescription  string    `json:"threat_app_description"`
	ThreatInformationFlow string    `json:"threat_information_flow"`
}

func (q *Queries) UpdateRiskAssessmentThreatStep(ctx context.Context, arg UpdateRiskAssessmentThreatStepParams) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, updateRiskAssessmentThreatStep, arg.ID, arg.ThreatAppDescription, arg.ThreatInformationFlow)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.AnalysisObject,
		&i.SecurityObjectives,
		&i.BusinessObjectives,
		&i.Type,
		&i.Status,
		&i.CurrentStep,
		&i.LastReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RiskOwnerID,
		&i.OrgID,
		&i.RefNum,
		&i.AcceptanceNote,
		&i.IsPublic,
		&i.ThreatAssessmentEnabled,
		&i.ThreatAppDescription,
		&i.ThreatInformationFlow,
	)
	return i, err
}

const updateRiskCurrentScores = `-- name: UpdateRiskCurrentScores :one
UPDATE risks
SET likelihood_current = $2, consequence_current = $3,
    likelihood_reasoning = $4, consequence_reasoning = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, assessment_id, name, likelihood_current, consequence_current, likelihood_target, consequence_target, risk_decision, status, created_at, updated_at, description, likelihood_reasoning, consequence_reasoning, owner_id, decision_notes, ref_num, review_needed, review_due, assessed_at, assessed_by, assessment_rationale
`

type UpdateRiskCurrentScoresParams struct {
	ID                   uuid.UUID     `json:"id"`
	LikelihoodCurrent    sql.NullInt32 `json:"likelihood_current"`
	ConsequenceCurrent   sql.NullInt32 `json:"consequence_current"`
	LikelihoodReasoning  string        `json:"likelihood_reasoning"`
	ConsequenceReasoning string        `json:"consequence_reasoning"`
}

func (q *Queries) UpdateRiskCurrentScores(ctx context.Context, arg UpdateRiskCurrentScoresParams) (Risk, error) {
	row := q.db.QueryRowContext(ctx, updateRiskCurrentScores,
		arg.ID,
		arg.LikelihoodCurrent,
		arg.ConsequenceCurrent,
		arg.LikelihoodReasoning,
		arg.ConsequenceReasoning,
	)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Name,
		&i.LikelihoodCurrent,
		&i.ConsequenceCurrent,
		&i.LikelihoodTarget,
		&i.ConsequenceTarget,
		&i.RiskDecision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LikelihoodReasoning,
		&i.ConsequenceReasoning,
		&i.OwnerID,
		&i.DecisionNotes,
		&i.RefNum,
		&i.ReviewNeeded,
		&i.ReviewDue,
		&i.AssessedAt,
		&i.AssessedBy,
		&i.AssessmentRationale,
	)
	return i, err
}

const updateRiskDecision = `-- name: UpdateRiskDecision :exec
UPDATE risks
SET risk_decision = $2, decision_notes = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateRiskDecisionParams struct {
	ID            uuid.UUID `json:"id"`
	RiskDecision  string    `json:"risk_decision"`
	DecisionNotes string    `json:"decision_notes"`
}

func (q *Queries) UpdateRiskDecision(ctx context.Context, arg UpdateRiskDecisionParams) error {
	_, err := q.db.ExecContext(ctx, updateRiskDecision, arg.ID, arg.RiskDecision, arg.DecisionNotes)
	return err
}

const updateRiskGlobalSettings = `-- name: UpdateRiskGlobalSettings :exec
UPDATE risk_global_settings
SET acceptance_criteria = $1, low_max = $2, high_min = $3
WHERE id = 1
`

type UpdateRiskGlobalSettingsParams struct {
	AcceptanceCriteria string `json:"acceptance_criteria"`
	LowMax             int32  `json:"low_max"`
	HighMin            int32  `json:"high_min"`
}

func (q *Queries) UpdateRiskGlobalSettings(ctx context.Context, arg UpdateRiskGlobalSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateRiskGlobalSettings, arg.AcceptanceCriteria, arg.LowMax, arg.HighMin)
	return err
}

const updateRiskIdentification = `-- name: UpdateRiskIdentification :one
UPDATE risks
SET name = $2, description = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, assessment_id, name, likelihood_current, consequence_current, likelihood_target, consequence_target, risk_decision, status, created_at, updated_at, description, likelihood_reasoning, consequence_reasoning, owner_id, decision_notes, ref_num, review_needed, review_due, assessed_at, assessed_by, assessment_rationale
`

type UpdateRiskIdentificationParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateRiskIdentification(ctx context.Context, arg UpdateRiskIdentificationParams) (Risk, error) {
	row := q.db.QueryRowContext(ctx, updateRiskIdentification, arg.ID, arg.Name, arg.Description)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Name,
		&i.LikelihoodCurrent,
		&i.ConsequenceCurrent,
		&i.LikelihoodTarget,
		&i.ConsequenceTarget,
		&i.RiskDecision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LikelihoodReasoning,
		&i.ConsequenceReasoning,
		&i.OwnerID,
		&i.DecisionNotes,
		&i.RefNum,
		&i.ReviewNeeded,
		&i.ReviewDue,
		&i.AssessedAt,
		&i.AssessedBy,
		&i.AssessmentRationale,
	)
	return i, err
}

const updateRiskTargetScore = `-- name: UpdateRiskTargetScore :exec
UPDATE risks
SET likelihood_target = $2, consequence_target = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateRiskTargetScoreParams struct {
	ID                uuid.UUID     `json:"id"`
	LikelihoodTarget  sql.NullInt32 `json:"likelihood_target"`
	ConsequenceTarget sql.NullInt32 `json:"consequence_target"`
}

func (q *Queries) UpdateRiskTargetScore(ctx context.Context, arg UpdateRiskTargetScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateRiskTargetScore, arg.ID, arg.LikelihoodTarget, arg.ConsequenceTarget)
	return err
}

const upsertRiskScaleLabel = `-- name: UpsertRiskScaleLabel :exec
INSERT INTO risk_scale_labels (scale, level, label, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (scale, level) DO UPDATE
    SET label = EXCLUDED.label, description = EXCLUDED.description
`

type UpsertRiskScaleLabelParams struct {
	Scale       string `json:"scale"`
	Level       int32  `json:"level"`
	Label       string `json:"label"`
	Description string `json:"description"`
}

func (q *Queries) UpsertRiskScaleLabel(ctx context.Context, arg UpsertRiskScaleLabelParams) error {
	_, err := q.db.ExecContext(ctx, upsertRiskScaleLabel,
		arg.Scale,
		arg.Level,
		arg.Label,
		arg.Description,
	)
	return err
}
